[package]
name = "platform-win"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
windows.workspace = true
shell-provider-protocol = { path = "../shell-provider-protocol" }
settings-store = { path = "../settings-store" }

[lints.rust]
unsafe_code = "allow"
