[package]
name = "notification-area-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
platform-win = { path = "../platform-win" }
serde_json.workspace = true
shell-provider-protocol = { path = "../shell-provider-protocol" }

[build-dependencies]
embed-resource.workspace = true
