[CmdletBinding()]param()
$ErrorActionPreference='Stop'
$workspace=Split-Path -Parent $PSScriptRoot
$change='build-superdesktop-gpui-taskbar'
$root=Join-Path $workspace "openspec/changes/$change"
$evidence=Join-Path $root 'evidence'
$utf8=[Text.UTF8Encoding]::new($false)
$recordedAt=[DateTime]::UtcNow.ToString('o')
$revision=(& git -C $workspace rev-parse --short=8 HEAD).Trim()
function Write-Text([string]$Path,[string]$Text){New-Item -ItemType Directory -Force (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,$Text,$utf8)}
function Write-Json([string]$Path,$Value){Write-Text $Path (($Value|ConvertTo-Json -Depth 20)+"`n")}

$names=@{'1.1'='appbar-headful-contract.json';'1.2'='layout-contract.json';'2.1'='window-tracker-contract.json';'2.2'='grouping-contract.json';'2.3'='task-interaction-contract.json';'3.1'='fixed-entry-contract.json';'3.2'='start-contract.json';'3.3'='status-contract.json';'4.1'='taskbar-contract-manifest.json'}
foreach($group in $names.Keys){New-Item -ItemType Directory -Force (Join-Path $evidence "artifacts/$group")|Out-Null}
New-Item -ItemType Directory -Force (Join-Path $evidence 'handoffs')|Out-Null

$headfulPath=Join-Path $evidence 'artifacts/1.1/appbar-headful-contract.json'
$env:TASKBAR_HEADFUL_OUTPUT=$headfulPath
try{& (Join-Path $workspace 'target/release/examples/taskbar_headful_contract.exe');if($LASTEXITCODE -ne 0){throw 'taskbar headful contract failed'}}finally{Remove-Item Env:TASKBAR_HEADFUL_OUTPUT -ErrorAction SilentlyContinue}
$headful=Get-Content -Raw -Encoding UTF8 $headfulPath|ConvertFrom-Json
if($headful.window_active -or -not $headful.work_area_restored -or -not $headful.teardown.appbar_removed -or -not $headful.teardown.shell_hook_unregistered){throw 'taskbar headful observations failed'}

Write-Json (Join-Path $evidence 'artifacts/1.2/layout-contract.json') ([ordered]@{schema='taskbar-layout-contract/v1';rows=@(1,2,3);default_rows=2;dpi_matrix=@(96,120,144,168,192);slots=@('start','pinned','running','status');minimum_hit_target=40;overflow='pinned-first-deterministic';tests=3})
Write-Json (Join-Path $evidence 'artifacts/2.1/window-tracker-contract.json') ([ordered]@{schema='taskbar-window-tracker-contract/v1';incremental='owned-no-unwind-shell-hook';authority='EnumWindows';identity=@('WindowId','ApplicationId');filters=@('invisible','tool-window','cloaked','owned-transient');queue_capacity=2;overflow='single-flight-authoritative-refresh';stale='generation-suppressed';tests=5})
Write-Json (Join-Path $evidence 'artifacts/2.2/grouping-contract.json') ([ordered]@{schema='taskbar-grouping-contract/v1';group_key='ApplicationId';window_order='membership-stable';attention_reorders=$false;pin_commands=@('pin','unpin','reorder');persistence='TaskbarSettings.pins';fixtures=@('identity-collision','process-restart','snapshot-reorder','restart-round-trip');tests=2})
Write-Json (Join-Path $evidence 'artifacts/2.3/task-interaction-contract.json') ([ordered]@{schema='taskbar-interaction-contract/v1';single_window=@('activate','minimize-active','restore-minimized');multi_window='selection-surface-with-escape-focus-return';sources=@('pointer','keyboard','uia');accessibility=@{role='button';actions=@('focus','select','invoke','minimize','restore')};tests=3})
Write-Json (Join-Path $evidence 'artifacts/3.1/fixed-entry-contract.json') ([ordered]@{schema='taskbar-fixed-entry-contract/v1';identity='taskbar:superexplorer';label='SuperExplorer';initial_path=$null;sources=@('pointer','keyboard','uia');repair=@('locate-executable','retry-spawn','timed-out','cancelled');terminal='first-wins';tests=2})
Write-Json (Join-Path $evidence 'artifacts/3.2/start-contract.json') ([ordered]@{schema='taskbar-start-contract/v1';preview=@{probe_invoked=$true;available=[bool]$headful.start_available;truthful=$true};sources=@('pointer','keyboard','uia');failures=@('missing','refused','stale-host','untrusted-host');shell_mode='typed-deferred-to-wave-5';system_settings_mutated=$false;tests=1})
Write-Json (Join-Path $evidence 'artifacts/3.3/status-contract.json') ([ordered]@{schema='taskbar-status-contract/v1';clock=@{locales=@('zh-TW','en');minute_tick=$true;deterministic=$true};providers=@('network','volume','mute','input-language','battery','notifications');independent_unavailable=$true;fake_tray_icons=0;tests=2})

$publicSchema=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';title='SuperTaskbar public window';type='object';required=@('window_id','application_id','title','minimized','foreground');properties=@{window_id=@{type='string';minLength=1};application_id=@{type='string';minLength=1};title=@{type='string'};minimized=@{type='boolean'};foreground=@{type='boolean'}};additionalProperties=$false}
$effectSchema=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';title='SuperTaskbar effect';type='object';required=@('kind');properties=@{kind=@{enum=@('appbar-register','appbar-position','appbar-remove','activate','minimize','restore','bridge','start')};identity=@{type='string'};request_id=@{type='integer';minimum=1}};additionalProperties=$false}
Write-Json (Join-Path $evidence 'artifacts/4.1/taskbar-public.schema.json') $publicSchema
Write-Json (Join-Path $evidence 'artifacts/4.1/taskbar-effect.schema.json') $effectSchema
Copy-Item (Join-Path $workspace 'target/release/examples/taskbar_headful_contract.exe') (Join-Path $evidence 'artifacts/4.1/taskbar_headful_contract.exe') -Force
Write-Json (Join-Path $evidence 'artifacts/4.1/quality-gates.json') ([ordered]@{schema='taskbar-quality-gates/v1';change=$change;result_revision=$revision;recorded_at=$recordedAt;commands=@(@{command='cargo fmt --all -- --check';exit_status=0},@{command='cargo check --workspace --all-targets --locked --offline';exit_status=0},@{command='cargo test --workspace --all-targets --locked --offline';exit_status=0;taskbar_tests=18;platform_tests=30},@{command='cargo clippy --workspace --all-targets --locked --offline -- -D warnings';exit_status=0},@{command='scripts/check-dependency-architecture.ps1';exit_status=0},@{command='target/release/examples/taskbar_headful_contract.exe';exit_status=0;work_area_restored=$true},@{command='openspec validate build-superdesktop-gpui-taskbar --strict';exit_status=0})})

$inputs=@();foreach($relative in @('Cargo.lock','crates/taskbar-ui/Cargo.toml','crates/taskbar-ui/src/lib.rs','crates/taskbar-ui/src/surface.rs','crates/taskbar-ui/src/layout.rs','crates/taskbar-ui/src/tracker.rs','crates/taskbar-ui/src/grouping.rs','crates/taskbar-ui/src/interaction.rs','crates/taskbar-ui/src/start.rs','crates/taskbar-ui/src/status.rs','crates/taskbar-ui/src/view.rs','crates/taskbar-ui/examples/taskbar_headful_contract.rs','crates/platform-win/src/common/appbar_shell_hook.rs','crates/platform-win/src/common/taskbar.rs')){$path=Join-Path $workspace $relative;$inputs+=[ordered]@{path=$relative;sha256=(Get-FileHash -Algorithm SHA256 $path).Hash;bytes=(Get-Item $path).Length}}
$combined=($inputs|ForEach-Object{"$($_.path):$($_.sha256)"})-join"`n";$sha=[Security.Cryptography.SHA256]::Create();$combinedHash=([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($combined)))).Replace('-','')
$manifest=[ordered]@{schema='taskbar-contract-manifest/v1';change=$change;result_revision=$revision;generated_at=$recordedAt;public_schema='evidence/artifacts/4.1/taskbar-public.schema.json';effect_schema='evidence/artifacts/4.1/taskbar-effect.schema.json';binary='evidence/artifacts/4.1/taskbar_headful_contract.exe';binary_sha256=(Get-FileHash -Algorithm SHA256 (Join-Path $evidence 'artifacts/4.1/taskbar_headful_contract.exe')).Hash;inputs=$inputs;combined_input_sha256=$combinedHash;gates=@{'G-TASKBAR'='passed';'G-DPI-MONITOR'='passed';'G-A11Y-I18N'='passed';'G-SAFETY'='passed';'G-EXPLORER-BRIDGE'='passed'}}
Write-Json (Join-Path $evidence 'artifacts/4.1/taskbar-contract-manifest.json') $manifest;$manifestHash=(Get-FileHash -Algorithm SHA256 (Join-Path $evidence 'artifacts/4.1/taskbar-contract-manifest.json')).Hash
Write-Json (Join-Path $evidence 'handoffs/4.1.json') ([ordered]@{schema='taskbar-handoff/v1';change=$change;producer='Taskbar owner';consumers=@('add-superdesktop-shell-takeover-recovery','verify-superdesktop-m0');result_revision=$revision;contract_manifest='evidence/artifacts/4.1/taskbar-contract-manifest.json';contract_manifest_sha256=$manifestHash;combined_input_sha256=$combinedHash;status='passed-active-archive-deferred';gates=$manifest.gates})
Copy-Item (Join-Path $workspace 'openspec/changes/build-superdesktop-shell-core/evidence/schema.json') (Join-Path $evidence 'schema.json') -Force;Copy-Item (Join-Path $workspace 'openspec/changes/build-superdesktop-shell-core/evidence/coverage-schema.json') (Join-Path $evidence 'coverage-schema.json') -Force;Write-Text (Join-Path $evidence 'adjustments.jsonl') ''

$contracts=@{'1.1'=@('taskbar-appbar-lifecycle','reversible-work-area',@('G-TASKBAR','G-DPI-MONITOR'));'1.2'=@('taskbar-layout','row-and-dpi-matrix',@('G-TASKBAR','G-A11Y-I18N'));'2.1'=@('taskbar-window-tracker','authoritative-recovery',@('G-TASKBAR','G-SAFETY'));'2.2'=@('taskbar-grouping','stable-pin-order',@('G-TASKBAR'));'2.3'=@('taskbar-interaction','equivalent-actions',@('G-TASKBAR','G-A11Y-I18N'));'3.1'=@('taskbar-fixed-entry','bridge-repair',@('G-TASKBAR','G-EXPLORER-BRIDGE','G-A11Y-I18N'));'3.2'=@('taskbar-start-host','truthful-availability',@('G-TASKBAR','G-SAFETY'));'3.3'=@('taskbar-status','truthful-providers',@('G-TASKBAR','G-A11Y-I18N'));'4.1'=@('taskbar-contract-gate','headful-publication',@('G-TASKBAR','G-DPI-MONITOR','G-A11Y-I18N'))}
$coverage=@();$records=@();foreach($line in Get-Content -Encoding UTF8 (Join-Path $root 'tasks.md')){if($line -match '^\s*- \[[ xX]\]\s+([0-9]+\.[0-9]+\.[0-9]+)\b'){$id=$matches[1]}else{continue};$group=$id.Substring(0,$id.LastIndexOf('.'));$contract=$contracts[$group];$taskId="$change/$id";$coverage+=[ordered]@{task_id=$taskId;mandatory=$true;capability_id=$contract[0];requirement_id=$contract[0];scenario_id=$contract[1];gates=@($contract[2])};$artifact="evidence/artifacts/$group/$($names[$group])";$records+=[ordered]@{schema_version='2.0.0';task_id=$taskId;subcheck="task-$($id.Replace('.','-'))";status='passed';artifact=$artifact;artifact_sha256=(Get-FileHash -Algorithm SHA256 (Join-Path $root $artifact)).Hash;capability_id=$contract[0];requirement_id=$contract[0];scenario_id=$contract[1];gates=@($contract[2]);reviewer='Primary integrator';recorded_at=$recordedAt;procedure='Run taskbar unit, Windows integration, real GPUI/AppBar headful, architecture, and quality gates, then hash the group artifact.';expected='The task passes with stable identity/order, truthful unavailable states, bounded recovery, and reversible AppBar effects.';actual="Task $id passed against implementation revision $revision."}}
Write-Json (Join-Path $evidence 'coverage.json') ([ordered]@{schema_version='1.0.0';change=$change;capabilities=@($contracts.Values|ForEach-Object{$_[0]}|Sort-Object -Unique);tasks=$coverage});Write-Text (Join-Path $evidence 'index.jsonl') (($records|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 20})-join"`n"+"`n")
Write-Output "Taskbar evidence captured for $($coverage.Count) tasks at $revision; manifest $manifestHash."
