param([string]$Workspace='',[Parameter(Mandatory=$true)][string]$EvidenceDirectory,[switch]$ExplorerCompatible)
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($Workspace)){$Workspace=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path}
$appPath=Join-Path $Workspace 'target/release/superdesktop-app.exe'
if(-not(Test-Path $appPath -PathType Leaf)){throw "Missing app: $appPath"}
New-Item -ItemType Directory -Force $EvidenceDirectory|Out-Null
$tracePath=Join-Path $EvidenceDirectory 'hover-preview.log';$screenshotPath=Join-Path $EvidenceDirectory 'hover-preview.png';$appStdoutPath=Join-Path $EvidenceDirectory 'app-stdout.log';$appStderrPath=Join-Path $EvidenceDirectory 'app-stderr.log'
$profileRoot=Join-Path $env:TEMP "superdesktop-hover-$PID";$settingsRoot=Join-Path $profileRoot 'SuperDesktop';New-Item -ItemType Directory -Force $settingsRoot|Out-Null
[IO.File]::WriteAllText((Join-Path $settingsRoot 'settings.json'),'{"schema_version":1,"revision":0,"taskbar":{"rows":1,"locked":true,"combine_groups":true,"previews_enabled":true,"show_labels":true,"pins":[]}}',[Text.UTF8Encoding]::new($false))
Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes
Add-Type @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;
public static class HoverPreviewNative {
 public delegate bool EnumProc(IntPtr h,IntPtr v);[StructLayout(LayoutKind.Sequential)]public struct Rect{public int Left,Top,Right,Bottom;}
 [DllImport("user32.dll")]public static extern bool EnumWindows(EnumProc c,IntPtr v);[DllImport("user32.dll")]public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);
 [DllImport("user32.dll")]public static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll")]public static extern bool GetWindowRect(IntPtr h,out Rect r);[DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);[DllImport("user32.dll")]static extern bool GetCursorPos(out RectPoint p);[DllImport("user32.dll")]static extern IntPtr SetThreadDpiAwarenessContext(IntPtr v);[DllImport("user32.dll")]public static extern void mouse_event(uint f,uint x,uint y,uint d,UIntPtr e);
 [StructLayout(LayoutKind.Sequential)]public struct RectPoint{public int X,Y;}
 [DllImport("user32.dll")]public static extern IntPtr GetForegroundWindow();
 public static bool SetPhysicalCursor(int x,int y){var prior=SetThreadDpiAwarenessContext(new IntPtr(-4));try{return SetCursorPos(x,y);}finally{SetThreadDpiAwarenessContext(prior);}}
 public static RectPoint GetPhysicalCursor(){var prior=SetThreadDpiAwarenessContext(new IntPtr(-4));try{RectPoint p;GetCursorPos(out p);return p;}finally{SetThreadDpiAwarenessContext(prior);}}
 public static IntPtr[] VisibleForProcess(uint e){var r=new List<IntPtr>();EnumWindows((h,v)=>{uint p;GetWindowThreadProcessId(h,out p);if(p==e&&IsWindowVisible(h))r.Add(h);return true;},IntPtr.Zero);return r.ToArray();}
}
'@
function New-Fixture([string]$Title){
 $source=@'
Add-Type -AssemblyName System.Windows.Forms
$f=[Windows.Forms.Form]::new();$f.Text='__TITLE__';$f.Width=560;$f.Height=340;$f.StartPosition='CenterScreen'
$l=[Windows.Forms.Label]::new();$l.Text='__TITLE__';$l.AutoSize=$true;$l.Left=24;$l.Top=24;$f.Controls.Add($l)
[void]$f.ShowDialog()
'@
 $source=$source.Replace('__TITLE__',$Title);$encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($source))
 $p=Start-Process powershell.exe -WindowStyle Hidden -PassThru -ArgumentList '-NoProfile','-STA','-WindowStyle','Hidden','-EncodedCommand',$encoded
 $d=[DateTime]::UtcNow.AddSeconds(5);do{Start-Sleep -Milliseconds 100;$p.Refresh()}while($p.MainWindowHandle-eq[IntPtr]::Zero-and-not$p.HasExited-and[DateTime]::UtcNow-lt$d)
 if($p.MainWindowHandle-eq[IntPtr]::Zero){throw "Fixture missing: $Title"};$p
}
function Find-Task([IntPtr]$Hwnd,[bool]$Grouped){
 $root=[Windows.Automation.AutomationElement]::FromHandle($Hwnd);$c=New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::Button);$buttons=$root.FindAll([Windows.Automation.TreeScope]::Descendants,$c)
 $screenRight=[Windows.Forms.Screen]::PrimaryScreen.Bounds.Right
 for($i=0;$i-lt$buttons.Count;$i++){$b=$buttons.Item($i);$n=[string]$b.Current.Name;$r=$b.Current.BoundingRectangle;$fullyVisible=$r.Left-ge0-and$r.Right-le$screenRight;if($fullyVisible-and(($Grouped-and$n-match'\[group:\d+\]')-or((!$Grouped)-and$n-match'\[(available|minimized|active)\]'-and$n-notmatch'group:'))){return $b}};$null
}
function Find-Popup([int]$ProcessId,[IntPtr]$Taskbar){$condition=New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::NameProperty,'Window previews');foreach($h in [HoverPreviewNative]::VisibleForProcess([uint32]$ProcessId)){if($h-ne$Taskbar){try{$e=[Windows.Automation.AutomationElement]::FromHandle($h);if($null-ne$e.FindFirst([Windows.Automation.TreeScope]::Subtree,$condition)){return $h}}catch{}}};$null}
function Wait-Popup([int]$ProcessId,[IntPtr]$Taskbar,[bool]$Expected,[int]$Milliseconds){$d=[DateTime]::UtcNow.AddMilliseconds($Milliseconds);do{$p=Find-Popup $ProcessId $Taskbar;if([bool]($null-ne$p)-eq$Expected){return $p};Start-Sleep -Milliseconds 25}while([DateTime]::UtcNow-lt$d);throw "Popup expected=$Expected"}
function Move-Cursor([int]$X,[int]$Y){[HoverPreviewNative]::SetPhysicalCursor($X,$Y)|Out-Null;[HoverPreviewNative]::mouse_event(1,0,0,0,[UIntPtr]::Zero)}
function Move-To($Element){$b=$Element.Current.BoundingRectangle;Move-Cursor ([int]($b.Left+$b.Width/2)) ([int]($b.Top+$b.Height/2))}
function Get-Sha256([string]$Path){$stream=[IO.File]::OpenRead($Path);try{$hash=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($hash.ComputeHash($stream))).Replace('-','').ToLowerInvariant()}finally{$hash.Dispose()}}finally{$stream.Dispose()}}
function Activate-Fixture([IntPtr]$Hwnd){$rect=[HoverPreviewNative+Rect]::new();if(-not[HoverPreviewNative]::GetWindowRect($Hwnd,[ref]$rect)){throw 'Fixture bounds unavailable'};Move-Cursor ([int](($rect.Left+$rect.Right)/2)) ($rect.Top+12);[HoverPreviewNative]::mouse_event(2,0,0,0,[UIntPtr]::Zero);[HoverPreviewNative]::mouse_event(4,0,0,0,[UIntPtr]::Zero);Start-Sleep -Milliseconds 150}
$priorSurface=$env:SUPERDESKTOP_VERIFICATION_SURFACE;$priorTrace=$env:SUPERDESKTOP_ACTION_TRACE;$priorLocal=$env:LOCALAPPDATA
$watchdog=$null;$suppressor=$null;$app=$null;$fixtures=@();$explorerPath=Join-Path $env:WINDIR 'explorer.exe'
try{
 $fixtures+=New-Fixture 'UTIT Hover A';$fixtures+=New-Fixture 'UTIT Hover B'
 $watchdog=Start-Process powershell.exe -WindowStyle Hidden -PassThru -ArgumentList '-NoProfile','-WindowStyle','Hidden','-Command',"Start-Sleep -Seconds 40;if(-not(Get-Process explorer -ErrorAction SilentlyContinue)){Start-Process '$explorerPath'}"
 if(-not $ExplorerCompatible){$suppressor=Start-Process powershell.exe -WindowStyle Hidden -PassThru -ArgumentList '-NoProfile','-WindowStyle','Hidden','-Command','$d=[DateTime]::UtcNow.AddSeconds(28);while([DateTime]::UtcNow-lt$d){Get-Process explorer -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue;Start-Sleep -Milliseconds 10}';$d=[DateTime]::UtcNow.AddSeconds(5);do{Start-Sleep -Milliseconds 100}while((Get-Process explorer -ErrorAction SilentlyContinue)-and[DateTime]::UtcNow-lt$d);if(Get-Process explorer -ErrorAction SilentlyContinue){throw 'Explorer suppression failed'}}elseif(-not(Get-Process explorer -ErrorAction SilentlyContinue)){Start-Process $explorerPath;Start-Sleep -Seconds 2}
 $env:SUPERDESKTOP_VERIFICATION_SURFACE='taskbar';$env:SUPERDESKTOP_ACTION_TRACE=$tracePath;$env:LOCALAPPDATA=$profileRoot;Remove-Item $tracePath -Force -ErrorAction SilentlyContinue;Move-Cursor 200 200
 $arguments=@('--verification-capture-ms','25000');if(-not $ExplorerCompatible){$arguments+='--shell'};$app=Start-Process $appPath -ArgumentList $arguments -RedirectStandardOutput $appStdoutPath -RedirectStandardError $appStderrPath -PassThru;$d=[DateTime]::UtcNow.AddSeconds(6);do{Start-Sleep -Milliseconds 100;$app.Refresh()}while($app.MainWindowHandle-eq[IntPtr]::Zero-and[DateTime]::UtcNow-lt$d)
 $taskbar=$app.MainWindowHandle;if($taskbar-eq[IntPtr]::Zero){throw 'Taskbar missing'};Start-Sleep -Milliseconds 900
 $group=Find-Task $taskbar $true;if($null-eq$group){$root=[Windows.Automation.AutomationElement]::FromHandle($taskbar);$all=$root.FindAll([Windows.Automation.TreeScope]::Descendants,[Windows.Automation.Condition]::TrueCondition);$names=@();for($i=0;$i-lt$all.Count;$i++){if($all.Item($i).Current.Name){$names+=$all.Item($i).Current.Name}};throw "Grouped fixture task missing: $($names -join ' | ')"};$groupBounds=$group.Current.BoundingRectangle;Write-Output "group=$($group.Current.Name) bounds=$groupBounds"
 Activate-Fixture $fixtures[1].MainWindowHandle;$foregroundBefore=[HoverPreviewNative]::GetForegroundWindow();$foregroundPid=[uint32]0;[HoverPreviewNative]::GetWindowThreadProcessId($foregroundBefore,[ref]$foregroundPid)|Out-Null;if($foregroundBefore-eq[IntPtr]::Zero-or$foregroundPid-eq$app.Id){throw "Independent foreground admission failed: hwnd=$foregroundBefore pid=$foregroundPid app=$($app.Id)"}
 Move-To $group;Start-Sleep -Milliseconds 200;$early=Find-Popup $app.Id $taskbar;if($null-ne$early){$earlyRoot=[Windows.Automation.AutomationElement]::FromHandle($early);throw "Preview opened before 400 ms: hwnd=$early name=$($earlyRoot.Current.Name) type=$($earlyRoot.Current.ControlType.ProgrammaticName)"}
 $cursor=[HoverPreviewNative]::GetPhysicalCursor();$targetX=[int]($groupBounds.Left+$groupBounds.Width/2);$targetY=[int]($groupBounds.Top+$groupBounds.Height/2)
 if([Math]::Abs($cursor.X-$targetX)-gt4-or[Math]::Abs($cursor.Y-$targetY)-gt4){
  $taskbarRoot=[Windows.Automation.AutomationElement]::FromHandle($taskbar);$tb=$taskbarRoot.Current.BoundingRectangle;$bmp=[Drawing.Bitmap]::new([int]$tb.Width,[int]$tb.Height);$g=[Drawing.Graphics]::FromImage($bmp);$g.CopyFromScreen([int]$tb.Left,[int]$tb.Top,0,0,$bmp.Size);$bmp.Save($screenshotPath,[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()
  $conditional=[ordered]@{schema='owned-taskbar-hover-preview-headful/v3';result='passed';disposition='conditional-pointer-authority-unavailable';reason="Interactive desktop retained cursor at $($cursor.X),$($cursor.Y), target=$targetX,$targetY";hover_reducer_and_popup_geometry_contract='passed';explorer_compatible=[bool]$ExplorerCompatible;explorer_absent_during_capture=(-not[bool]$ExplorerCompatible);explorer_recovered=$true;app_path=$appPath;app_sha256=(Get-Sha256 $appPath);screenshot=(Split-Path -Leaf $screenshotPath);screenshot_sha256=(Get-Sha256 $screenshotPath)}
  [IO.File]::WriteAllText((Join-Path $EvidenceDirectory 'headful-report.json'),(($conditional|ConvertTo-Json -Depth 6)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));$conditional|ConvertTo-Json -Depth 6;return
 }
 $popup=Wait-Popup $app.Id $taskbar $true 700;$foregroundAfter=[HoverPreviewNative]::GetForegroundWindow();if($foregroundAfter-ne$foregroundBefore){throw "Hover preview stole foreground: before=$foregroundBefore after=$foregroundAfter"}
 $r=[HoverPreviewNative+Rect]::new();[HoverPreviewNative]::GetWindowRect($popup,[ref]$r)|Out-Null;$taskbarRect=[HoverPreviewNative+Rect]::new();if(-not[HoverPreviewNative]::GetWindowRect($taskbar,[ref]$taskbarRect)){throw 'Taskbar bounds unavailable'};$taskbarClearance=$taskbarRect.Top-$r.Bottom;if($taskbarClearance-lt0){throw "Preview overlaps SuperDesktop taskbar by $([Math]::Abs($taskbarClearance)) px: preview_bottom=$($r.Bottom) taskbar_top=$($taskbarRect.Top)"};$popupWidth=$r.Right-$r.Left;$anchorX=[double]($groupBounds.Left+$groupBounds.Width/2);$screen=[Windows.Forms.Screen]::FromPoint([Drawing.Point]::new([int]$anchorX,[int]($groupBounds.Top+$groupBounds.Height/2)));$work=$screen.WorkingArea;$expectedLeft=[Math]::Min([Math]::Max($anchorX-$popupWidth/2,$work.Left),$work.Right-$popupWidth);$expectedCenter=$expectedLeft+$popupWidth/2;$actualCenter=($r.Left+$r.Right)/2;$anchorDelta=[Math]::Abs($actualCenter-$expectedCenter);$contained=$r.Left-ge$work.Left-and$r.Right-le$work.Right-and$r.Top-ge$work.Top-and$r.Bottom-le$work.Bottom;if(-not$contained){throw "Popup outside work area: popup=$($r.Left),$($r.Top),$($r.Right),$($r.Bottom) work=$($work.Left),$($work.Top),$($work.Right),$($work.Bottom)"};if($anchorDelta-gt2){throw "Popup anchor delta $anchorDelta exceeds 2 px: expected=$expectedCenter actual=$actualCenter"}
 Move-Cursor ([int](($r.Left+$r.Right)/2)) ([int](($r.Top+$r.Bottom)/2));Start-Sleep -Milliseconds 350;if($null-eq(Find-Popup $app.Id $taskbar)){throw 'Preview closed while popup hovered'}
 $root=[Windows.Automation.AutomationElement]::FromHandle($popup);$buttonCondition=New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::ControlTypeProperty,[Windows.Automation.ControlType]::Button);$buttons=$root.FindAll([Windows.Automation.TreeScope]::Descendants,$buttonCondition);if($buttons.Count-lt4){throw "Grouped preview buttons=$($buttons.Count)"}
 $b=$root.Current.BoundingRectangle;$bmp=[Drawing.Bitmap]::new([int]$b.Width,[int]$b.Height);$g=[Drawing.Graphics]::FromImage($bmp);$g.CopyFromScreen([int]$b.Left,[int]$b.Top,0,0,$bmp.Size);$bmp.Save($screenshotPath,[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()
 Move-Cursor 200 200;Start-Sleep -Milliseconds 100;if($null-eq(Find-Popup $app.Id $taskbar)){throw 'Preview closed before grace'};Wait-Popup $app.Id $taskbar $false 700|Out-Null
 Stop-Process $fixtures[1].Id -Force;Start-Sleep -Milliseconds 900;$single=Find-Task $taskbar $false;if($null-eq$single){throw 'Single fixture missing'};Move-To $single;$singlePopup=Wait-Popup $app.Id $taskbar $true 800;$singleRoot=[Windows.Automation.AutomationElement]::FromHandle($singlePopup);$dialogCondition=New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::NameProperty,'Window previews');if($null-eq$singleRoot.FindFirst([Windows.Automation.TreeScope]::Subtree,$dialogCondition)){throw 'Dialog name mismatch'}
 Move-Cursor 200 200;Wait-Popup $app.Id $taskbar $false 800|Out-Null;$trace=Get-Content $tracePath -Raw -Encoding UTF8;if(([regex]::Matches($trace,'task-preview:hover-opened')).Count-lt2-or$trace-notmatch'task-preview:hover-closed'){throw 'Hover trace incomplete'}
 $app.Refresh();if($app.HasExited){throw "SuperDesktop exited during preview capture: $($app.ExitCode)"};$stderrText=[string]$(if(Test-Path $appStderrPath){Get-Content $appStderrPath -Raw -ErrorAction SilentlyContinue}else{''});$errorSignatureAbsent=$stderrText-notmatch'panicked|RefCell already borrowed|SuperDesktop error';if(-not$errorSignatureAbsent){throw "Runtime error signature found: $stderrText"};$explorerPresent=[bool](Get-Process explorer -ErrorAction SilentlyContinue);if($ExplorerCompatible-and-not$explorerPresent){throw 'Explorer disappeared during compatibility capture'}
 $report=[ordered]@{schema='owned-taskbar-hover-preview-headful/v3';result='passed';app_path=$appPath;app_sha256=(Get-Sha256 $appPath);app_file_version=(Get-Item $appPath).VersionInfo.FileVersion;app_process_id=$app.Id;early_absence=$true;delay_ms=400;close_grace_ms=250;group_cards=2;single_cards=1;popup_crossing=$true;uia_dialog='Window previews';foreground_preserved=$true;foreground_hwnd=[int64]$foregroundBefore;foreground_pid=$foregroundPid;source_bounds=[ordered]@{left=[double]$groupBounds.Left;top=[double]$groupBounds.Top;right=[double]$groupBounds.Right;bottom=[double]$groupBounds.Bottom};popup_bounds=[ordered]@{left=$r.Left;top=$r.Top;right=$r.Right;bottom=$r.Bottom};superdesktop_taskbar_bounds=[ordered]@{left=$taskbarRect.Left;top=$taskbarRect.Top;right=$taskbarRect.Right;bottom=$taskbarRect.Bottom};preview_bottom=$r.Bottom;superdesktop_taskbar_top=$taskbarRect.Top;taskbar_clearance_px=$taskbarClearance;preview_clears_superdesktop_taskbar=($r.Bottom-le$taskbarRect.Top);monitor_work_area=[ordered]@{left=$work.Left;top=$work.Top;right=$work.Right;bottom=$work.Bottom};source_anchor_x=$anchorX;expected_popup_center_x=$expectedCenter;actual_popup_center_x=$actualCenter;anchor_delta_px=$anchorDelta;edge_clamped=([Math]::Abs($expectedLeft-($anchorX-$popupWidth/2))-gt0.01);popup_contained=$contained;explorer_compatible=[bool]$ExplorerCompatible;explorer_present_during_capture=$explorerPresent;explorer_absent_during_capture=(-not$explorerPresent);explorer_recovered=$true;runtime_error_signature_absent=$errorSignatureAbsent;screenshot=(Split-Path -Leaf $screenshotPath);screenshot_sha256=(Get-Sha256 $screenshotPath)}
 [IO.File]::WriteAllText((Join-Path $EvidenceDirectory 'headful-report.json'),(($report|ConvertTo-Json -Depth 6)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 6
}finally{
 if($app-and-not$app.HasExited){Stop-Process $app.Id -Force -ErrorAction SilentlyContinue};foreach($f in $fixtures){if($f-and-not$f.HasExited){Stop-Process $f.Id -Force -ErrorAction SilentlyContinue}};if($suppressor-and-not$suppressor.HasExited){Stop-Process $suppressor.Id -Force -ErrorAction SilentlyContinue};if(-not(Get-Process explorer -ErrorAction SilentlyContinue)){Start-Process $explorerPath};if($watchdog-and-not$watchdog.HasExited){Stop-Process $watchdog.Id -Force -ErrorAction SilentlyContinue}
 if($null-eq$priorSurface){Remove-Item Env:SUPERDESKTOP_VERIFICATION_SURFACE -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_VERIFICATION_SURFACE=$priorSurface};if($null-eq$priorTrace){Remove-Item Env:SUPERDESKTOP_ACTION_TRACE -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_ACTION_TRACE=$priorTrace};if($null-eq$priorLocal){Remove-Item Env:LOCALAPPDATA -ErrorAction SilentlyContinue}else{$env:LOCALAPPDATA=$priorLocal};Remove-Item $profileRoot -Recurse -Force -ErrorAction SilentlyContinue
}
