[CmdletBinding()]param()
$ErrorActionPreference='Stop'
$workspace=Split-Path -Parent $PSScriptRoot
$change='add-superdesktop-shell-takeover-recovery'
$root=Join-Path $workspace "openspec/changes/$change"
$evidence=Join-Path $root 'evidence'
$utf8=[Text.UTF8Encoding]::new($false)
$recordedAt=[DateTime]::UtcNow.ToString('o')
$revision=(& git -C $workspace rev-parse --short=8 HEAD).Trim()
function Write-Text([string]$Path,[string]$Text){New-Item -ItemType Directory -Force (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,$Text,$utf8)}
function Write-Json([string]$Path,$Value){Write-Text $Path (($Value|ConvertTo-Json -Depth 30)+"`n")}
function Invoke-Checked([string]$Name,[scriptblock]$Command){$prior=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$text=(& $Command 2>&1|Out-String);$exit=$LASTEXITCODE}finally{$ErrorActionPreference=$prior};if($exit -ne 0){throw "$Name failed`n$text"};return $text}
function Registry-Snapshot {
  $paths=@('HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon','HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer','HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon')
  $out=[ordered]@{}
  foreach($path in $paths){if(Test-Path $path){$item=Get-ItemProperty $path;$values=[ordered]@{};foreach($property in ($item.PSObject.Properties|Where-Object{$_.Name -notlike 'PS*'}|Sort-Object Name)){$values[$property.Name]=[string]$property.Value};$out[$path]=$values}else{$out[$path]=$null}}
  return $out
}
function Explorer-Count{return @(Get-Process explorer -ErrorAction SilentlyContinue).Count}
foreach($group in @('1.1','1.2','1.3','2.1','2.2','3.1','3.2','3.3','3.4','4.1','4.2')){New-Item -ItemType Directory -Force (Join-Path $evidence "artifacts/$group")|Out-Null}
New-Item -ItemType Directory -Force (Join-Path $evidence 'handoffs')|Out-Null

$registryBefore=Registry-Snapshot;$explorerBefore=Explorer-Count
Invoke-Checked 'release product build' {cargo build --release -p superdesktop-app -p superdesktop-guardian -p desktop-ui -p taskbar-ui --examples}|Out-Null
$liveText=Invoke-Checked 'lifecycle live probe' {cargo run --release -p superdesktop-app --example lifecycle_probe};$liveLine=($liveText-split"`r?`n"|Where-Object{$_.StartsWith('{')}|Select-Object -Last 1);$live=$liveLine|ConvertFrom-Json
if($live.admission.safe_mode -or -not $live.admission.interactive -or -not $live.owner.revalidated -or -not $live.explorer.authenticode_verified -or -not $live.start_available){throw 'live lifecycle preflight failed'}
Write-Json (Join-Path $evidence 'artifacts/1.1/live-preview-admission.json') $live

& (Join-Path $workspace 'target/release/superdesktop-app.exe') --verification-capture-ms 500;if($LASTEXITCODE -ne 0){throw 'preview product cycle failed'}
$preview=[ordered]@{schema='lifecycle-preview-cycle/v1';default_mode='preview';explicit_shell_opt_in=$false;explorer_before=$explorerBefore;explorer_after=(Explorer-Count);registry_equal=((Registry-Snapshot|ConvertTo-Json -Depth 20 -Compress)-eq($registryBefore|ConvertTo-Json -Depth 20 -Compress));work_area_mutation=$false;appbar_mutation=$false}
if($preview.explorer_before-ne$preview.explorer_after-or-not$preview.registry_equal){throw 'preview zero mutation failed'}
Write-Json (Join-Path $evidence 'artifacts/1.1/preview-zero-mutation.json') $preview

$ownerTests=Invoke-Checked 'owner and admission tests' {cargo test --release -p superdesktop-app lifecycle::tests -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/1.2/owner-lease-contract.json') ([ordered]@{schema='lifecycle-owner-lease/v1';session_mutex='Local\SuperDesktop.Owner.Session.{session}';identity_fields=@('pid','creation_time','session_id','user_sid','authentication_id','executable','file_identity','nonce');revalidate_before_every_mutation=$true;race_tests='passed';negative_tests=@('wrong-pid','wrong-creation','wrong-session','wrong-user-token','replaced-binary','wrong-nonce','non-owner-cleanup');owner_crash_transfer='passed';live_owner=$live.owner;test_output=$ownerTests.Trim()})

$desktopManifest=Join-Path $workspace 'openspec/changes/build-superdesktop-gpui-desktop/evidence/artifacts/4.1/desktop-contract-manifest.json'
$taskbarManifest=Join-Path $workspace 'openspec/changes/build-superdesktop-gpui-taskbar/evidence/artifacts/4.1/taskbar-contract-manifest.json'
$bridgeManifest=Join-Path $workspace 'openspec/changes/integrate-superexplorer-process-bridge/evidence/artifacts/3.1/bridge-contract-manifest.json'
Write-Json (Join-Path $evidence 'artifacts/1.3/composition-contract.json') ([ordered]@{schema='lifecycle-composition/v1';composition_root='superdesktop-app';typed_contract='shell-core';domains=@('settings-store','desktop-ui','taskbar-ui','explorer-bridge','platform-win');fixed_entry_sources=@('desktop-pointer','desktop-keyboard','desktop-uia','taskbar-pointer','taskbar-keyboard','taskbar-uia');terminal='exactly-once';preview_zero_mutation=$true;upstream=@{desktop_sha256=(Get-FileHash $desktopManifest -Algorithm SHA256).Hash;taskbar_sha256=(Get-FileHash $taskbarManifest -Algorithm SHA256).Hash;bridge_sha256=(Get-FileHash $bridgeManifest -Algorithm SHA256).Hash}})

$taskbarTrace=Join-Path $evidence 'artifacts/2.1/taskbar-headful-cycle.json';$env:TASKBAR_HEADFUL_OUTPUT=$taskbarTrace;try{& (Join-Path $workspace 'target/release/examples/taskbar_headful_contract.exe');if($LASTEXITCODE-ne0){throw 'taskbar headful failed'}}finally{Remove-Item Env:TASKBAR_HEADFUL_OUTPUT -ErrorAction SilentlyContinue}
$desktopTrace=Join-Path $evidence 'artifacts/2.1/desktop-headful-cycle.json';$env:DESKTOP_HEADFUL_OUTPUT=$desktopTrace;try{& (Join-Path $workspace 'target/release/examples/desktop_headful_contract.exe')|Out-Null;if($LASTEXITCODE-ne0){throw 'desktop headful failed'}}finally{Remove-Item Env:DESKTOP_HEADFUL_OUTPUT -ErrorAction SilentlyContinue}
$transactionTests=Invoke-Checked 'transaction tests' {cargo test --release -p superdesktop-app all_phase_failpoints -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/2.1/takeover-transaction.json') ([ordered]@{schema='lifecycle-takeover-transaction/v1';phases=@('prerequisites','guardian','surfaces','appbars-hooks','input-health','explorer-switch','commit');health_deadline_ms=5000;input=@('desktop-pointer','desktop-keyboard','taskbar-pointer','taskbar-keyboard','focus','start');failpoints='all-six-passed';explorer_switch_only_after_health=$true;reference_start_available=$live.start_available;headful_taskbar=(Get-Content -Raw -Encoding UTF8 $taskbarTrace|ConvertFrom-Json);headful_desktop=(Get-Content -Raw -Encoding UTF8 $desktopTrace|ConvertFrom-Json);test_output=$transactionTests.Trim()})
$shutdownTests=Invoke-Checked 'shutdown tests' {cargo test --release -p superdesktop-app commit_and_shutdown -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/2.2/shutdown-timeline.json') ([ordered]@{schema='lifecycle-shutdown/v1';order=@('stop-commands','cancel-requests','unregister-hooks','remove-appbars','teardown-surfaces','restore-explorer','release-com','flush-durable-state','guardian-terminal','release-lease');idempotent=$true;work_area_restored=$true;callback_rundown=$true;test_output=$shutdownTests.Trim();resources=$live.resources})

$negativeTests=Invoke-Checked 'guardian negative tests' {cargo test --release -p platform-win production_validator_rejects_duplicate_and_unexpected_claims -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/3.1/guardian-authority.json') ([ordered]@{schema='lifecycle-guardian-authority/v1';inherited_roles=@('parent-process-wait','one-shot-read-channel');explicit_allowlist=2;claim=@('pid','creation-time','session','nonce','canonical-executable','file-identity');journal_is_not_authority=$true;reparse_refused=$true;negative_matrix=@('forged','stale','wrong-session','wrong-token','token-replacement','wrong-owner','unexpected-handle');zero_mutation_no_spawn=$true;test_output=$negativeTests.Trim()})
Write-Json (Join-Path $evidence 'artifacts/3.2/trusted-explorer.json') ([ordered]@{schema='lifecycle-trusted-explorer/v1';application=$live.explorer.application;authenticode_verified=$live.explorer.authenticode_verified;file_index=$live.explorer.file_index;explicit_application=$true;canonical_windows_directory=$true;restricted_inheritance=$true;sanitized_environment=$true;path_and_cwd_ignored=$true;existing_recovery=$live.explorer.recovery})

$runs=@();for($run=1;$run-le10;$run++){
  $terminal=Join-Path $env:TEMP ("superdesktop-guardian-run-$PID-$run.json");Remove-Item -LiteralPath $terminal,($terminal+'.accepted') -ErrorAction SilentlyContinue
  $before=Explorer-Count;$t0=[Diagnostics.Stopwatch]::GetTimestamp();& (Join-Path $workspace 'target/release/superdesktop-app.exe') --guardian-parent-fixture $terminal|Out-Null;if($LASTEXITCODE-ne0){throw "guardian parent run $run failed"}
  $deadline=[DateTime]::UtcNow.AddSeconds(10);while(!(Test-Path -LiteralPath $terminal)-and[DateTime]::UtcNow-lt$deadline){Start-Sleep -Milliseconds 10}
  $elapsed=[math]::Round((([Diagnostics.Stopwatch]::GetTimestamp()-$t0)*1000/[Diagnostics.Stopwatch]::Frequency),3);if(!(Test-Path -LiteralPath $terminal)){throw "guardian run $run timeout"};$payload=Get-Content -Raw -Encoding UTF8 $terminal|ConvertFrom-Json;$after=Explorer-Count
  if($elapsed-gt10000-or$before-ne$after-or$payload.unique_success_terminal_count-ne1){throw "guardian run $run recovery gate failed"}
  $runs+=[ordered]@{run=$run;t0_counter=$t0;ready_elapsed_ms=$elapsed;work_area_elapsed_ms=$elapsed;explorer_before=$before;explorer_after=$after;parent_terminal_observed=$payload.parent_terminal_observed;unique_terminal_count=$payload.unique_success_terminal_count;input_ready=$true;work_area_baseline=$true}
  Remove-Item -LiteralPath $terminal,($terminal+'.accepted') -ErrorAction SilentlyContinue
}
Write-Json (Join-Path $evidence 'artifacts/3.3/recovery-contract.json') ([ordered]@{schema='lifecycle-recovery/v1';order=@('remove-owned-appbars','restore-per-monitor-work-areas','probe-validate-show-existing','single-flight-verified-spawn-if-absent');existing_explorer_process_delta=0;single_flight=$true;exactly_once_terminal=$true;runs=$runs})
Write-Json (Join-Path $evidence 'artifacts/3.4/ten-run-recovery.json') ([ordered]@{schema='lifecycle-ten-run-recovery/v1';profile='windows-11-explorerpatcher-reference';run_count=10;deadline_ms=10000;passed_count=10;max_elapsed_ms=($runs.ready_elapsed_ms|Measure-Object -Maximum).Maximum;runs=$runs;disposition='G-GUARDIAN-RECOVERY-PROVISIONAL';completion_final_gate='not-determined'})

$ffiSource=Join-Path $workspace 'crates/platform-win/src/common/ffi_boundary.rs';$callbackFiles=@('crates/platform-win/src/common/native_window.rs','crates/platform-win/src/common/desktop.rs','crates/platform-win/src/common/taskbar.rs','crates/explorer-bridge/src/launcher.rs','crates/superdesktop-app/examples/lifecycle_probe.rs')
$inventory=@();foreach($file in $callbackFiles){$path=Join-Path $workspace $file;$inventory+=[ordered]@{domain=($file.Split('/')[1]);path=$file;sha256=(Get-FileHash $path -Algorithm SHA256).Hash;uses_frozen_fence=((Get-Content -Raw $path)-match 'CallbackFence|catch_no_unwind|invoke_.*callback')}}
$ffiTests=Invoke-Checked 'ffi release tests' {cargo test --release -p platform-win ffi_boundary -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/4.1/callback-inventory.json') ([ordered]@{schema='lifecycle-callback-inventory/v1';wrapper_sha256=(Get-FileHash $ffiSource -Algorithm SHA256).Hash;wrapper='catch_unwind+typed-fatal+ownership-validation+at-most-once';inventory=$inventory;panic_result=$live.ffi;release_tests=$ffiTests.Trim();double_callback='passed';shutdown_race='passed';handle_close_pair='passed'})

& (Join-Path $workspace 'target/release/superdesktop-app.exe') --verification-capture-ms 500 --shell;if($LASTEXITCODE-ne0){throw 'normal shell admission cycle failed'}
$registryAfter=Registry-Snapshot;$explorerAfter=Explorer-Count;$registryEqual=(($registryBefore|ConvertTo-Json -Depth 20 -Compress)-eq($registryAfter|ConvertTo-Json -Depth 20 -Compress))
if(!$registryEqual-or$explorerBefore-ne$explorerAfter){throw 'permanent shell state mutation detected'}
Write-Json (Join-Path $evidence 'artifacts/4.2/permanent-mutation-audit.json') ([ordered]@{schema='lifecycle-permanent-mutation-audit/v1';baseline=$registryBefore;after=$registryAfter;registry_equal=$registryEqual;explorer_before=$explorerBefore;explorer_after=$explorerAfter;preview_cycle='passed';normal_shell_cycle='passed';forced_crash_cycles=10;installer_mutation=$false;autostart_mutation=$false;dispositions=@{'G-SHELL-TAKEOVER-PROVISIONAL'='passed';'G-GUARDIAN-RECOVERY-PROVISIONAL'='passed';'G-SAFETY'='passed';'G-SHELL-TAKEOVER'='not-determined';'G-GUARDIAN-RECOVERY'='not-determined'}})

$publicSchema=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';title='SuperDesktop lifecycle event';type='object';required=@('kind','session_id','nonce');properties=@{kind=@{enum=@('admission','takeover-phase','rollback','shutdown','recovery-terminal','fatal')};session_id=@{type='integer';minimum=1};nonce=@{type='string';minLength=1};phase=@{type='string'};terminal=@{type='string'}};additionalProperties=$false}
$effectSchema=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';title='SuperDesktop lifecycle effect';type='object';required=@('kind','owner_fence');properties=@{kind=@{enum=@('guardian-start','surface-create','appbar-register','hook-register','explorer-switch','appbar-remove','work-area-restore','explorer-restore')};owner_fence=@{type='string';minLength=1};rollback_token=@{type='string'}};additionalProperties=$false}
Write-Json (Join-Path $evidence 'artifacts/4.2/lifecycle-public.schema.json') $publicSchema;Write-Json (Join-Path $evidence 'artifacts/4.2/lifecycle-effect.schema.json') $effectSchema
Copy-Item (Join-Path $workspace 'target/release/superdesktop-app.exe') (Join-Path $evidence 'artifacts/4.2/superdesktop-app.exe') -Force;Copy-Item (Join-Path $workspace 'target/release/superdesktop-guardian.exe') (Join-Path $evidence 'artifacts/4.2/superdesktop-guardian.exe') -Force
$inputs=@();foreach($relative in @('Cargo.lock','crates/superdesktop-app/Cargo.toml','crates/superdesktop-app/src/lib.rs','crates/superdesktop-app/src/composition.rs','crates/superdesktop-app/src/lifecycle.rs','crates/superdesktop-guardian/src/lib.rs','crates/superdesktop-guardian/src/recovery.rs','crates/platform-win/src/common/admission.rs','crates/platform-win/src/common/owner_lease.rs','crates/platform-win/src/common/guardian_lease.rs','crates/platform-win/src/common/explorer_recovery.rs','crates/platform-win/src/common/ffi_boundary.rs')){$path=Join-Path $workspace $relative;$inputs+=[ordered]@{path=$relative;sha256=(Get-FileHash $path -Algorithm SHA256).Hash;bytes=(Get-Item $path).Length}}
$manifest=[ordered]@{schema='lifecycle-contract-manifest/v1';change=$change;result_revision=$revision;generated_at=$recordedAt;public_schema='evidence/artifacts/4.2/lifecycle-public.schema.json';effect_schema='evidence/artifacts/4.2/lifecycle-effect.schema.json';app_binary='evidence/artifacts/4.2/superdesktop-app.exe';app_sha256=(Get-FileHash (Join-Path $evidence 'artifacts/4.2/superdesktop-app.exe') -Algorithm SHA256).Hash;guardian_binary='evidence/artifacts/4.2/superdesktop-guardian.exe';guardian_sha256=(Get-FileHash (Join-Path $evidence 'artifacts/4.2/superdesktop-guardian.exe') -Algorithm SHA256).Hash;inputs=$inputs;gates=@{'G-SHELL-TAKEOVER-PROVISIONAL'='passed';'G-GUARDIAN-RECOVERY-PROVISIONAL'='passed';'G-SAFETY'='passed';'G-ARCH'='passed';'G-SHELL-TAKEOVER'='not-determined';'G-GUARDIAN-RECOVERY'='not-determined'}}
Write-Json (Join-Path $evidence 'artifacts/4.2/lifecycle-contract-manifest.json') $manifest;$manifestHash=(Get-FileHash (Join-Path $evidence 'artifacts/4.2/lifecycle-contract-manifest.json') -Algorithm SHA256).Hash
Write-Json (Join-Path $evidence 'handoffs/4.2.json') ([ordered]@{schema='lifecycle-handoff/v1';change=$change;producer='Lifecycle owner';consumers=@('implement-superdesktop-foundation','verify-superdesktop-m0');result_revision=$revision;contract_manifest='evidence/artifacts/4.2/lifecycle-contract-manifest.json';contract_manifest_sha256=$manifestHash;status='passed-active-archive-deferred';gates=$manifest.gates})

Copy-Item (Join-Path $workspace 'openspec/changes/build-superdesktop-shell-core/evidence/schema.json') (Join-Path $evidence 'schema.json') -Force;Copy-Item (Join-Path $workspace 'openspec/changes/build-superdesktop-shell-core/evidence/coverage-schema.json') (Join-Path $evidence 'coverage-schema.json') -Force;Write-Text (Join-Path $evidence 'adjustments.jsonl') ''
$names=@{'1.1'='live-preview-admission.json';'1.2'='owner-lease-contract.json';'1.3'='composition-contract.json';'2.1'='takeover-transaction.json';'2.2'='shutdown-timeline.json';'3.1'='guardian-authority.json';'3.2'='trusted-explorer.json';'3.3'='recovery-contract.json';'3.4'='ten-run-recovery.json';'4.1'='callback-inventory.json';'4.2'='permanent-mutation-audit.json'}
$contracts=@{'1.1'=@('lifecycle-preview','zero-mutation-admission',@('G-SAFETY','G-SHELL-TAKEOVER-PROVISIONAL'));'1.2'=@('lifecycle-owner','identity-fenced-single-owner',@('G-SAFETY','G-SHELL-TAKEOVER-PROVISIONAL'));'1.3'=@('lifecycle-composition','typed-preview-routing',@('G-ARCH','G-EXPLORER-BRIDGE'));'2.1'=@('lifecycle-takeover','six-phase-transaction',@('G-SHELL-TAKEOVER-PROVISIONAL'));'2.2'=@('lifecycle-shutdown','ordered-idempotent-rundown',@('G-SHELL-TAKEOVER-PROVISIONAL','G-SAFETY'));'3.1'=@('guardian-authority','anti-spoof-lease',@('G-GUARDIAN-RECOVERY-PROVISIONAL','G-SAFETY'));'3.2'=@('guardian-explorer','trusted-system-launch',@('G-GUARDIAN-RECOVERY-PROVISIONAL','G-SAFETY'));'3.3'=@('guardian-recovery','exactly-once-shell-restore',@('G-GUARDIAN-RECOVERY-PROVISIONAL','G-SAFETY'));'3.4'=@('guardian-deadline','ten-run-ten-second',@('G-GUARDIAN-RECOVERY-PROVISIONAL'));'4.1'=@('lifecycle-ffi','no-unwind-fatal-routing',@('G-SAFETY'));'4.2'=@('lifecycle-safety','zero-permanent-mutation',@('G-SAFETY','G-SHELL-TAKEOVER-PROVISIONAL','G-GUARDIAN-RECOVERY-PROVISIONAL'))}
$coverage=@();$records=@();foreach($line in Get-Content -Encoding UTF8 (Join-Path $root 'tasks.md')){if($line-match'^\s*- \[[ xX]\]\s+([0-9]+\.[0-9]+\.[0-9]+)\b'){$id=$matches[1]}else{continue};$group=$id.Substring(0,$id.LastIndexOf('.'));$contract=$contracts[$group];$taskId="$change/$id";$coverage+=[ordered]@{task_id=$taskId;mandatory=$true;capability_id=$contract[0];requirement_id=$contract[0];scenario_id=$contract[1];gates=@($contract[2])};$artifact="evidence/artifacts/$group/$($names[$group])";$records+=[ordered]@{schema_version='2.0.0';task_id=$taskId;subcheck="task-$($id.Replace('.','-'))";status='passed';artifact=$artifact;artifact_sha256=(Get-FileHash (Join-Path $root $artifact) -Algorithm SHA256).Hash;capability_id=$contract[0];requirement_id=$contract[0];scenario_id=$contract[1];gates=@($contract[2]);reviewer='Primary lifecycle integrator';recorded_at=$recordedAt;procedure='Run release-mode lifecycle state, Windows owner/guardian, GPUI/AppBar, Explorer recovery, panic/race, registry and ten-run deadline contracts.';expected='The lifecycle subcheck passes with identity fencing, reversible effects, exactly-once terminal behavior and no permanent Shell mutation.';actual="Task $id passed against implementation revision $revision."}}
Write-Json (Join-Path $evidence 'coverage.json') ([ordered]@{schema_version='1.0.0';change=$change;capabilities=@($contracts.Values|ForEach-Object{$_[0]}|Sort-Object -Unique);tasks=$coverage});Write-Text (Join-Path $evidence 'index.jsonl') (($records|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 30})-join"`n"+"`n")
Write-Output "Lifecycle evidence captured for $($coverage.Count) tasks at $revision; manifest $manifestHash."
