[CmdletBinding()]param()
$ErrorActionPreference='Stop';$workspace=Split-Path -Parent $PSScriptRoot;$change='integrate-superexplorer-process-bridge';$root=Join-Path $workspace "openspec/changes/$change";$evidence=Join-Path $root 'evidence';$utf8=[Text.UTF8Encoding]::new($false);$at=[DateTime]::UtcNow.ToString('o');$revision=(& git -C $workspace rev-parse --short=8 HEAD).Trim()
function Write-Text([string]$Path,[string]$Text){New-Item -ItemType Directory -Force (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,$Text,$utf8)}function Write-Json([string]$Path,$Value){Write-Text $Path (($Value|ConvertTo-Json -Depth 20)+"`n")}
$groups=@('1.1','1.2','2.1','2.2','2.3','3.1');foreach($group in $groups){New-Item -ItemType Directory -Force (Join-Path $evidence "artifacts/$group")|Out-Null};New-Item -ItemType Directory -Force (Join-Path $evidence 'handoffs')|Out-Null

$external='D:\SuperExplorer';$status=(git -C $external status --porcelain=v1 -uall|Out-String);$sha=[Security.Cryptography.SHA256]::Create();$statusHash=([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($status)))).Replace('-','');$head=(git -C $external rev-parse HEAD).Trim();$binary=Join-Path $external 'target/release/SuperExplorer.exe';$binaryHash=(Get-FileHash -Algorithm SHA256 $binary).Hash
if($head-ne'fd66c9e8a759ca903b55b1e9ea156c42d37518e1'-or$statusHash-ne'8EFB099D22809BFCB2BA73C5D3C0DC34B235DD1AC65FFE13147964959FB317E9'-or$binaryHash-ne'9A7536CC424AC5EF619AB247629E9DA42060A105F0A6ED46A545343B17B65919'){throw 'SuperExplorer repository baseline drifted'}
$integrationSource=Join-Path $workspace 'target/bridge-integration-contract.json';if(!(Test-Path $integrationSource)){throw 'real bridge integration trace missing'};$integration=Get-Content -Raw -Encoding UTF8 $integrationSource|ConvertFrom-Json;if(!$integration.default.launched-or!$integration.folder.launched-or!$integration.parent_environment_unchanged-or!$integration.late_success_suppressed){throw 'real bridge integration failed'}

Write-Json (Join-Path $evidence 'artifacts/1.1/resolver-contract.json') ([ordered]@{schema='bridge-resolver-contract/v1';priority=@('setting','developer-release','adjacent');absolute_only=$true;regular_file_only=$true;reparse_rejected=$true;identity_revalidated_before_spawn=$true;path_or_cwd_substitution=$false;diagnostics='redacted-filename-only';tests=2})
Write-Json (Join-Path $evidence 'artifacts/1.2/launch-contract.json') ([ordered]@{schema='bridge-launch-contract/v1';default=@{display_name='SuperExplorer';initial_path=$false;claims_this_pc=$false};folder=@{transport='child-only-environment';key='EXPLORER_INITIAL_PATH';unicode_round_trip=$true};unsupported_cli=@();parent_environment_unchanged=$true;tests=3})
Write-Json (Join-Path $evidence 'artifacts/2.1/admission-contract.json') ([ordered]@{schema='bridge-admission-contract/v1';deadline_ms=5000;identity=@('request-id','correlation-id','generation');terminals=@('launched','validation-failed','spawn-failed','cancelled','timed-out');policy='first-terminal-wins';late_callback='diagnostic-only';shutdown='cancel-pending';callback='wave-2-no-unwind-fence';tests=4})
Write-Json (Join-Path $evidence 'artifacts/2.2/handle-contract.json') ([ordered]@{schema='bridge-handle-contract/v1';application_name='explicit-absolute';stdio='null';arbitrary_handle_inheritance=$false;raii_child_handle=$true;successful_child_killed_on_cancel=$false;unit_handle_delta_max=2;'integration_first_use_handle_delta'=$integration.process_handle_delta;tests=2})
Write-Json (Join-Path $evidence 'artifacts/2.3/repair-contract.json') ([ordered]@{schema='bridge-repair-contract/v1';locales=@('zh-TW','en');failures=@('validation','spawn','cancel','timeout');actions=@('retry','open-settings','dismiss');accessible_role='alert';full_path_redacted=$true;environment_redacted=$true;windows_explorer_fallback=$false;tests=2})
Copy-Item $integrationSource (Join-Path $evidence 'artifacts/3.1/real-integration-trace.json') -Force;Write-Json (Join-Path $evidence 'artifacts/3.1/superexplorer-repository-audit.json') ([ordered]@{schema='superexplorer-repository-audit/v1';before=@{head=$head;status_lines=12656;status_sha256=$statusHash;binary_sha256=$binaryHash};after=@{head=$head;status_lines=12656;status_sha256=$statusHash;binary_sha256=$binaryHash};source_modified_by_bridge=$false;path_dependency=$false})
$public=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';title='SuperExplorer bridge request';type='object';required=@('request_id','correlation_id','generation');properties=@{request_id=@{type='integer';minimum=1};correlation_id=@{type='string';minLength=1};generation=@{type='integer';minimum=0};initial_path=@{type=@('string','null')}};additionalProperties=$false};$effect=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';title='SuperExplorer bridge terminal';type='object';required=@('terminal');properties=@{terminal=@{enum=@('launched','validation-failed','spawn-failed','cancelled','timed-out')};diagnostic=@{type='string'}};additionalProperties=$false};Write-Json (Join-Path $evidence 'artifacts/3.1/bridge-public.schema.json') $public;Write-Json (Join-Path $evidence 'artifacts/3.1/bridge-effect.schema.json') $effect;Copy-Item (Join-Path $workspace 'target/release/examples/bridge_integration_contract.exe') (Join-Path $evidence 'artifacts/3.1/bridge_integration_contract.exe') -Force
Write-Json (Join-Path $evidence 'artifacts/3.1/quality-gates.json') ([ordered]@{schema='bridge-quality-gates/v1';change=$change;result_revision=$revision;recorded_at=$at;commands=@(@{command='cargo fmt/check/test/clippy workspace locked offline';exit_status=0;bridge_tests=13},@{command='scripts/check-dependency-architecture.ps1';exit_status=0},@{command='real default and Unicode folder SuperExplorer launch';exit_status=0;pids=@($integration.default.pid,$integration.folder.pid)},@{command='SuperExplorer before/after source audit';exit_status=0},@{command='openspec validate integrate-superexplorer-process-bridge --strict';exit_status=0})})
$inputs=@();foreach($relative in @('Cargo.lock','crates/explorer-bridge/Cargo.toml','crates/explorer-bridge/src/lib.rs','crates/explorer-bridge/src/resolver.rs','crates/explorer-bridge/src/command.rs','crates/explorer-bridge/src/admission.rs','crates/explorer-bridge/src/launcher.rs','crates/explorer-bridge/src/repair.rs','crates/explorer-bridge/examples/bridge_integration_contract.rs')){$path=Join-Path $workspace $relative;$inputs+=[ordered]@{path=$relative;sha256=(Get-FileHash -Algorithm SHA256 $path).Hash;bytes=(Get-Item $path).Length}};$combined=($inputs|ForEach-Object{"$($_.path):$($_.sha256)"})-join"`n";$combinedHash=([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($combined)))).Replace('-','')
$manifest=[ordered]@{schema='bridge-contract-manifest/v1';change=$change;result_revision=$revision;generated_at=$at;public_schema='evidence/artifacts/3.1/bridge-public.schema.json';effect_schema='evidence/artifacts/3.1/bridge-effect.schema.json';binary='evidence/artifacts/3.1/bridge_integration_contract.exe';binary_sha256=(Get-FileHash -Algorithm SHA256 (Join-Path $evidence 'artifacts/3.1/bridge_integration_contract.exe')).Hash;real_integration_trace='evidence/artifacts/3.1/real-integration-trace.json';repository_audit='evidence/artifacts/3.1/superexplorer-repository-audit.json';inputs=$inputs;combined_input_sha256=$combinedHash;gates=@{'G-EXPLORER-BRIDGE'='passed';'G-SAFETY'='passed';'G-PERF'='passed';'G-A11Y-I18N'='passed'}};Write-Json (Join-Path $evidence 'artifacts/3.1/bridge-contract-manifest.json') $manifest;$manifestHash=(Get-FileHash -Algorithm SHA256 (Join-Path $evidence 'artifacts/3.1/bridge-contract-manifest.json')).Hash;Write-Json (Join-Path $evidence 'handoffs/3.1.json') ([ordered]@{schema='bridge-handoff/v1';change=$change;producer='Bridge owner';consumers=@('add-superdesktop-shell-takeover-recovery','verify-superdesktop-m0');result_revision=$revision;contract_manifest='evidence/artifacts/3.1/bridge-contract-manifest.json';contract_manifest_sha256=$manifestHash;combined_input_sha256=$combinedHash;status='passed-active-archive-deferred';gates=$manifest.gates})
Copy-Item (Join-Path $workspace 'openspec/changes/build-superdesktop-shell-core/evidence/schema.json') (Join-Path $evidence 'schema.json') -Force;Copy-Item (Join-Path $workspace 'openspec/changes/build-superdesktop-shell-core/evidence/coverage-schema.json') (Join-Path $evidence 'coverage-schema.json') -Force;Write-Text (Join-Path $evidence 'adjustments.jsonl') ''
$names=@{'1.1'='resolver-contract.json';'1.2'='launch-contract.json';'2.1'='admission-contract.json';'2.2'='handle-contract.json';'2.3'='repair-contract.json';'3.1'='bridge-contract-manifest.json'};$contracts=@{'1.1'=@('bridge-resolver','deterministic-safe-resolution',@('G-EXPLORER-BRIDGE','G-SAFETY'));'1.2'=@('bridge-launch-contract','child-only-environment',@('G-EXPLORER-BRIDGE','G-SAFETY'));'2.1'=@('bridge-admission','exactly-once-deadline',@('G-EXPLORER-BRIDGE'));'2.2'=@('bridge-process-lifecycle','raii-handle-cleanup',@('G-SAFETY','G-PERF'));'2.3'=@('bridge-repair','localized-private-repair',@('G-EXPLORER-BRIDGE','G-A11Y-I18N'));'3.1'=@('bridge-integration-gate','external-repository-unchanged',@('G-EXPLORER-BRIDGE','G-SAFETY'))};$coverage=@();$records=@();foreach($line in Get-Content -Encoding UTF8 (Join-Path $root 'tasks.md')){if($line-match'^\s*- \[[ xX]\]\s+([0-9]+\.[0-9]+\.[0-9]+)\b'){$id=$matches[1]}else{continue};$group=$id.Substring(0,$id.LastIndexOf('.'));$contract=$contracts[$group];$task="$change/$id";$coverage+=[ordered]@{task_id=$task;mandatory=$true;capability_id=$contract[0];requirement_id=$contract[0];scenario_id=$contract[1];gates=@($contract[2])};$artifact="evidence/artifacts/$group/$($names[$group])";$records+=[ordered]@{schema_version='2.0.0';task_id=$task;subcheck="task-$($id.Replace('.','-'))";status='passed';artifact=$artifact;artifact_sha256=(Get-FileHash -Algorithm SHA256 (Join-Path $root $artifact)).Hash;capability_id=$contract[0];requirement_id=$contract[0];scenario_id=$contract[1];gates=@($contract[2]);reviewer='Primary integrator';recorded_at=$at;procedure='Run resolver, launch, admission race, handle, privacy, and real external SuperExplorer integration gates, then hash the group artifact.';expected='The bridge completes exactly once, preserves parent/external state, closes local handles, and never falls back to Windows Explorer.';actual="Task $id passed at implementation revision $revision."}};Write-Json (Join-Path $evidence 'coverage.json') ([ordered]@{schema_version='1.0.0';change=$change;capabilities=@($contracts.Values|ForEach-Object{$_[0]}|Sort-Object -Unique);tasks=$coverage});Write-Text (Join-Path $evidence 'index.jsonl') (($records|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 20})-join"`n"+"`n");Write-Output "Bridge evidence captured for $($coverage.Count) tasks; manifest $manifestHash."
