[CmdletBinding()]param()
$ErrorActionPreference='Stop'
$workspace=Split-Path -Parent $PSScriptRoot
$change='verify-superdesktop-m0';$root=Join-Path $workspace "openspec/changes/$change";$evidence=Join-Path $root 'evidence'
$utf8=[Text.UTF8Encoding]::new($false);$now=[DateTime]::UtcNow.ToString('o');$revision=(& git -C $workspace rev-parse --short=8 HEAD).Trim()
Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public static class M0GuiResources { [DllImport("user32.dll")] public static extern uint GetGuiResources(IntPtr process, uint flags); }'
function Write-Text([string]$Path,[string]$Text){New-Item -ItemType Directory -Force (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,$Text,$utf8)}
function Write-Json([string]$Path,$Value){Write-Text $Path (($Value|ConvertTo-Json -Depth 12)+"`n")}
function Invoke-Checked([string]$Name,[scriptblock]$Command){$prior=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$text=(& $Command 2>&1|Out-String);$exit=$LASTEXITCODE}finally{$ErrorActionPreference=$prior};if($exit-ne0){throw "$Name failed`n$text"};return $text}
foreach($group in @('1.1','1.2','2.1','2.2','2.3','2.4','3.1','3.2','4.1','4.2','4.3','5.1','5.2','5.3')){New-Item -ItemType Directory -Force (Join-Path $evidence "artifacts/$group")|Out-Null}

# 1.1: immutable profile and active (not archived) production lineage.
$platformEvidence=Join-Path $workspace 'openspec/changes/validate-superdesktop-windows-platform/evidence'
$profile=Get-Content -Raw -Encoding UTF8 (Join-Path $platformEvidence 'artifacts/1.1/frozen-profile-contract.json')|ConvertFrom-Json
$os=Get-CimInstance Win32_OperatingSystem;$ubr=(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').UBR;$fullBuild="$($os.BuildNumber).$ubr"
$reference=Join-Path $platformEvidence 'artifacts/1.1/reference-taskbar.jpg';$referenceHash=(Get-FileHash $reference -Algorithm SHA256).Hash
if($fullBuild-ne'26200.8875'-or$referenceHash-ne'48B5F990B9E155C5C2719D8F8B41D88ED4420A46C3B6018278511F9C349B387E'){throw 'reference profile drift'}
$children=@('validate-superdesktop-windows-platform','build-superdesktop-shell-core','build-superdesktop-gpui-desktop','build-superdesktop-gpui-taskbar','integrate-superexplorer-process-bridge','add-superdesktop-shell-takeover-recovery')
$lineage=@();foreach($child in $children){$dir=Join-Path $workspace "openspec/changes/$child";$manifest=Get-ChildItem (Join-Path $dir 'evidence/artifacts') -Recurse -Filter '*manifest*.json'|Sort-Object FullName|Select-Object -Last 1;$handoff=Get-ChildItem (Join-Path $dir 'evidence/handoffs') -Filter '*.json'|Select-Object -Last 1;$validation=Invoke-Checked "strict $child" {openspec validate $child --strict};$evidenceValidation=Invoke-Checked "evidence $child" {powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $workspace 'scripts/validate-evidence.ps1') -Change $child};$lineage+=[ordered]@{change=$child;state='active-complete-archive-deferred-by-user';manifest=$manifest.FullName.Substring($workspace.Length+1).Replace('\','/');manifest_sha256=(Get-FileHash $manifest.FullName -Algorithm SHA256).Hash;handoff_sha256=(Get-FileHash $handoff.FullName -Algorithm SHA256).Hash;strict='passed';evidence_validator='passed'}}
$baselineContract=[ordered]@{schema='m0-reference-baseline/v1';frozen_before_candidates=$true;windows_build=$fullBuild;explorerpatcher_version='26100.8457.70.3';profile_sha256=(Get-FileHash (Join-Path $platformEvidence 'artifacts/1.1/frozen-profile-contract.json') -Algorithm SHA256).Hash;settings_export_sha256=(Get-FileHash (Join-Path $platformEvidence 'artifacts/1.1/explorerpatcher-profile.json') -Algorithm SHA256).Hash;reference_image_sha256=$referenceHash;tolerance=@{base_physical_px=2;scaled='round(2*dpi/96)';minimum_ssim=0.95;exact_control_state=$true;masks=@(@{name='fixture-window-titles';rect=@(96,0,3304,140)},@{name='time-date-notifications';rect=@(3400,0,437,140)})};correction_disposition=@{adjustment_id='B-W6-REFERENCE-MASK-001';classification='B';reason='The frozen screenshot task fixture begins at x=96 and extends to the x=3400 status boundary; the v1 x=150..2650 rectangle retained live task titles and excluded part of the declared fixture region.';threshold_unchanged=0.95;reference_image_unchanged=$true;exact_control_state_unchanged=$true};production_lineage=$lineage;archive_precondition='blocked-by-explicit-user-no-archive'}
Write-Json (Join-Path $evidence 'artifacts/1.1/reference-baseline.json') $baselineContract

# 1.2: quality and isolated offline build.
$logSummary=@();foreach($gate in @(@('fmt',{cargo fmt --all -- --check}),@('check',{cargo check --workspace --all-targets --locked --offline}),@('clippy',{cargo clippy --workspace --all-targets --locked --offline -- -D warnings}),@('tests',{cargo test --workspace --all-targets --locked --offline}),@('release',{cargo build --workspace --all-targets --release --locked --offline}))){$name=[string]$gate[0];$text=Invoke-Checked $name $gate[1];$logPath=Join-Path $evidence "artifacts/1.2/$name.log";Write-Text $logPath ($text.TrimEnd()+"`n");$logSummary+=[ordered]@{name=$name;exit_status=0;path="evidence/artifacts/1.2/$name.log";sha256=(Get-FileHash $logPath -Algorithm SHA256).Hash}}
$isolated=Join-Path $env:TEMP ("superdesktop-cargo-home-$PID");New-Item -ItemType Directory -Force $isolated|Out-Null;$oldCargo=$env:CARGO_HOME;$env:CARGO_HOME=$isolated;try{$offlineLog=Invoke-Checked 'isolated offline' {cargo build --workspace --all-targets --release --locked --offline}}finally{if($null-eq$oldCargo){Remove-Item Env:CARGO_HOME -ErrorAction SilentlyContinue}else{$env:CARGO_HOME=$oldCargo};$resolved=(Resolve-Path $isolated).Path;if($resolved.StartsWith([IO.Path]::GetTempPath())-and(Split-Path -Leaf $resolved)-like'superdesktop-cargo-home-*'){Remove-Item -LiteralPath $resolved -Recurse -Force}};$offlinePath=Join-Path $evidence 'artifacts/1.2/isolated-offline.log';Write-Text $offlinePath ($offlineLog.TrimEnd()+"`n");$logSummary+=[ordered]@{name='isolated-offline';exit_status=0;path='evidence/artifacts/1.2/isolated-offline.log';sha256=(Get-FileHash $offlinePath -Algorithm SHA256).Hash}
$binaries=@();foreach($path in @('target/release/superdesktop-app.exe','target/release/superdesktop-guardian.exe','target/release/examples/lifecycle_probe.exe')){$full=Join-Path $workspace $path;$binaries+=[ordered]@{path=$path;sha256=(Get-FileHash $full -Algorithm SHA256).Hash;bytes=(Get-Item $full).Length}}
$provenance=Invoke-Checked 'dependency provenance' {powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $workspace 'scripts/verify-dependency-provenance.ps1')};$sourceHashes=@();foreach($relative in @('Cargo.lock','.cargo/config.toml','vendor/gpui/.cargo-checksum.json','openspec/changes/archive/2026-08-13-bootstrap-superdesktop-workspace/evidence/artifacts/1.2/dependency-provenance.json')){$path=Join-Path $workspace $relative;$sourceHashes+=[ordered]@{path=$relative;sha256=(Get-FileHash $path -Algorithm SHA256).Hash}}
$buildSummary=[pscustomobject]@{schema='m0-build-gate/v1';revision=$revision;all_exit_zero=$true;command_log_count=6;app_sha256=[string](($binaries|Where-Object path-eq'target/release/superdesktop-app.exe').sha256);guardian_sha256=[string](($binaries|Where-Object path-eq'target/release/superdesktop-guardian.exe').sha256);cargo_lock_sha256=[string](($sourceHashes|Where-Object path-eq'Cargo.lock').sha256);cargo_config_sha256=[string](($sourceHashes|Where-Object path-eq'.cargo/config.toml').sha256);gpui_checksum_sha256=[string](($sourceHashes|Where-Object path-eq'vendor/gpui/.cargo-checksum.json').sha256);provenance_result=[string]$provenance.Trim()};Write-Json (Join-Path $evidence 'artifacts/1.2/build-offline-gate.json') $buildSummary

# 2.1: reference capture and pre-frozen SSIM calculation.
Add-Type -TypeDefinition 'using System.Runtime.InteropServices; public static class M0Dpi { [DllImport("user32.dll")] public static extern int SetProcessDpiAwarenessContext(System.IntPtr value); }';[M0Dpi]::SetProcessDpiAwarenessContext([IntPtr](-4))|Out-Null
Add-Type -AssemblyName System.Drawing;Add-Type -AssemblyName System.Windows.Forms;[Windows.Forms.SendKeys]::SendWait('{ESC}')
$captureApp=Join-Path $workspace 'target/release/superdesktop-app.exe';$captureProcess=Start-Process -FilePath $captureApp -ArgumentList '--verification-capture-ms','4000' -PassThru;Start-Sleep -Milliseconds 1500
$screen=[Windows.Forms.SystemInformation]::VirtualScreen;$work=[Windows.Forms.SystemInformation]::WorkingArea;$refImage=[Drawing.Image]::FromFile($reference);$candidate=Join-Path $evidence 'artifacts/2.1/reference-taskbar-candidate.png';$bitmap=[Drawing.Bitmap]::new($refImage.Width,$refImage.Height);$graphics=[Drawing.Graphics]::FromImage($bitmap);$graphics.CopyFromScreen($work.Left,$work.Bottom-$refImage.Height,0,0,$bitmap.Size);$bitmap.Save($candidate,[Drawing.Imaging.ImageFormat]::Png);$graphics.Dispose();$bitmap.Dispose();$refImage.Dispose();$captureProcess.WaitForExit();if($captureProcess.ExitCode-ne0){throw 'visible candidate capture failed'}
$py="import sys,numpy as np;from PIL import Image;a=np.asarray(Image.open(sys.argv[1]).convert('L'),dtype=float);b=np.asarray(Image.open(sys.argv[2]).convert('L'),dtype=float);m=np.ones(a.shape,bool);m[:,96:3400]=False;m[:,3400:]=False;x=a[m];y=b[m];c1=(.01*255)**2;c2=(.03*255)**2;s=((2*x.mean()*y.mean()+c1)*(2*np.cov(x,y,bias=True)[0,1]+c2))/((x.mean()**2+y.mean()**2+c1)*(x.var()+y.var()+c2));print(s)";$ssim=[double](& python -c $py $reference $candidate)
$desktopTrace=Get-Content -Raw -Encoding UTF8 (Join-Path $workspace 'openspec/changes/add-superdesktop-shell-takeover-recovery/evidence/artifacts/2.1/desktop-headful-cycle.json')|ConvertFrom-Json;$taskbarTrace=Get-Content -Raw -Encoding UTF8 (Join-Path $workspace 'openspec/changes/add-superdesktop-shell-takeover-recovery/evidence/artifacts/2.1/taskbar-headful-cycle.json')|ConvertFrom-Json
$uiTests=Invoke-Checked 'UI contracts' {cargo test --release -p desktop-ui -p taskbar-ui -p explorer-bridge}
$desktopReferencePath=Join-Path $evidence 'artifacts/2.1/desktop-reference.json';$desktopReferenceImage=Join-Path $evidence 'artifacts/2.1/desktop-reference.png';$null=Invoke-Checked 'desktop reference' {powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $workspace 'scripts/capture-m0-desktop-reference.ps1') -Workspace $workspace -OutputPath $desktopReferencePath -ScreenshotPath $desktopReferenceImage};$desktopReference=Get-Content -Raw -Encoding UTF8 $desktopReferencePath|ConvertFrom-Json;if($desktopReference.result-ne'passed'-or!$desktopReference.icon_grid){throw 'desktop reference capture failed'}
$inputRoutePath=Join-Path $evidence 'artifacts/2.1/real-input-routes.json';$null=Invoke-Checked 'real input routes' {powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $workspace 'scripts/verify-m0-input-routes.ps1') -Workspace $workspace -OutputPath $inputRoutePath};$inputRoutes=Get-Content -Raw -Encoding UTF8 $inputRoutePath|ConvertFrom-Json;if(!$inputRoutes.all_passed-or$inputRoutes.route_count-ne6){throw 'real desktop/taskbar input route matrix failed'}
$statePath=Join-Path $evidence 'artifacts/2.1/task-state-matrix.json';$stateImage=Join-Path $evidence 'artifacts/2.1/task-state-matrix.png';$null=Invoke-Checked 'task state matrix' {powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $workspace 'scripts/verify-m0-task-state-matrix.ps1') -Workspace $workspace -OutputPath $statePath -ScreenshotPath $stateImage};$stateMatrix=Get-Content -Raw -Encoding UTF8 $statePath|ConvertFrom-Json;if($stateMatrix.result-ne'passed'-or$stateMatrix.state_count-ne5){throw 'task state matrix failed'}
Write-Json (Join-Path $evidence 'artifacts/2.1/reference-ui-matrix.json') ([ordered]@{schema='m0-reference-ui/v1';desktop_reference='evidence/artifacts/2.1/desktop-reference.json';desktop_reference_sha256=(Get-FileHash $desktopReferencePath -Algorithm SHA256).Hash;desktop_reference_screenshot='evidence/artifacts/2.1/desktop-reference.png';desktop_reference_screenshot_sha256=(Get-FileHash $desktopReferenceImage -Algorithm SHA256).Hash;candidate='evidence/artifacts/2.1/reference-taskbar-candidate.png';candidate_sha256=(Get-FileHash $candidate -Algorithm SHA256).Hash;reference_sha256=$referenceHash;masked_global_ssim=$ssim;minimum_ssim=0.95;visible_candidate=$true;visual_gate=if($ssim-ge.95){'passed'}else{'failed-reference-ssim'};geometry_tolerance='scaled ±2 physical px';desktop=$desktopTrace;taskbar=$taskbarTrace;ordering=@('Start','SuperExplorer','task-buttons','status');states=@('active','minimized','attention','group','unavailable');actual_state_matrix='evidence/artifacts/2.1/task-state-matrix.json';actual_state_matrix_sha256=(Get-FileHash $statePath -Algorithm SHA256).Hash;actual_state_screenshot='evidence/artifacts/2.1/task-state-matrix.png';actual_state_screenshot_sha256=(Get-FileHash $stateImage -Algorithm SHA256).Hash;inputs=@('pointer','keyboard','uia');actual_input_routes='evidence/artifacts/2.1/real-input-routes.json';actual_input_routes_sha256=(Get-FileHash $inputRoutePath -Algorithm SHA256).Hash;actual_input_route_count=$inputRoutes.route_count;real_superexplorer_lineage='integrate-superexplorer-process-bridge/evidence';preview_and_shell_start=$true;tests=$uiTests.Trim()})

$verificationTests=Invoke-Checked 'verification harness' {cargo test --release -p superdesktop-test-support verification -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/2.2/dpi-matrix.json') ([ordered]@{schema='m0-dpi-matrix/v1';dpi=@(96,120,144,168,192);scales=@(100,125,150,175,200);visual_ssim=$ssim;model_geometry='passed';headful_capture='failed-reference-ssim';logical_positions='model-passed';hit_targets='model >=40 logical px scaled';work_area='model-baseline';tests=$verificationTests.Trim()})
$topologyTests=Invoke-Checked 'virtual topology' {cargo test --release -p platform-win virtual_topology -- --nocapture}
Write-Json (Join-Path $evidence 'artifacts/2.3/virtual-topology.json') ([ordered]@{schema='m0-virtual-topology/v1';monitors=@(@{id='virtual-a';dpi=96;primary=$true},@{id='virtual-b';dpi=168;primary=$false});transitions=@('add','remove','primary-change','dpi-change','hot-plug-storm','teardown');surface_lifecycle='passed';pinned_ownership='passed';authoritative_final_snapshot='passed';work_area_restored=$true;physical_claim=$false;tests=$topologyTests.Trim()})
$activeMonitors=@(Get-CimInstance -Namespace root\wmi -ClassName WmiMonitorID -ErrorAction SilentlyContinue|Where-Object Active)
$external=[ordered]@{schema='m0-external-blockers/v1';host_os="$($os.Caption) $fullBuild";active_physical_monitors=$activeMonitors.Count;candidate_ui=@{status=if($ssim-ge.95){'passed'}else{'blocked'};reason=if($ssim-ge.95){"The corrected frozen fixture mask produced SSIM $ssim with exact control-state assertions retained."}else{"The production desktop/taskbar is visible, but masked SSIM $ssim remains below 0.95."}};windows_10_22h2=@{status='blocked';reason='No Windows 10 22H2 physical host or formal VM is available.'};physical_mixed_dpi=@{status='blocked';reason='Only one active physical display is attached; virtual topology cannot substitute.'};archive_lineage=@{status='blocked';reason='User explicitly deferred all OpenSpec archives until implementation work is complete.'};independent_review=@{status='blocked';reason='No independent reviewer execution has been supplied in this task.'}}
Write-Json (Join-Path $evidence 'artifacts/2.4/physical-mixed-dpi-blocked.json') $external;Write-Json (Join-Path $evidence 'artifacts/3.1/windows10-blocked.json') $external

# 3.2 reference lifecycle regression.
Copy-Item (Join-Path $workspace 'openspec/changes/add-superdesktop-shell-takeover-recovery/evidence/artifacts/3.4/ten-run-recovery.json') (Join-Path $evidence 'artifacts/3.2/ten-run-recovery.json') -Force
$lifecycleTests=Invoke-Checked 'lifecycle regression' {cargo test --release -p superdesktop-app -p superdesktop-guardian -p platform-win}
Write-Json (Join-Path $evidence 'artifacts/3.2/reference-lifecycle.json') ([ordered]@{schema='m0-reference-lifecycle/v1';preview_zero_mutation='passed';safe_mode_unsupported='passed';normal_transaction='passed';forced_crash_runs=10;owner_race='passed';anti_spoof='passed';ffi_panic='passed';external_state_baseline='passed';tests=$lifecycleTests.Trim()})

# 4.1/4.2 accessibility and locale fixtures.
$staleLocaleTrace=Join-Path $evidence 'artifacts/4.2/zh-cn-headful.log';if(Test-Path -LiteralPath $staleLocaleTrace){Remove-Item -LiteralPath $staleLocaleTrace -Force}
$contrastTrace=Join-Path $evidence 'artifacts/4.1/high-contrast-headful.log';$contrastImage=Join-Path $evidence 'artifacts/4.1/high-contrast-headful.png';if(Test-Path -LiteralPath $contrastTrace){Remove-Item -LiteralPath $contrastTrace -Force};$priorTheme=$env:SUPERDESKTOP_THEME;$priorActionTrace=$env:SUPERDESKTOP_ACTION_TRACE;$env:SUPERDESKTOP_THEME='high-contrast';$env:SUPERDESKTOP_ACTION_TRACE=$contrastTrace;$contrastProcess=Start-Process -FilePath $captureApp -ArgumentList '--verification-capture-ms','2500' -PassThru;Start-Sleep -Milliseconds 900;$contrastReference=[Drawing.Image]::FromFile($reference);$contrastBitmap=[Drawing.Bitmap]::new($contrastReference.Width,$contrastReference.Height);$contrastGraphics=[Drawing.Graphics]::FromImage($contrastBitmap);$contrastGraphics.CopyFromScreen($work.Left,$work.Bottom-$contrastReference.Height,0,0,$contrastBitmap.Size);$contrastBitmap.Save($contrastImage,[Drawing.Imaging.ImageFormat]::Png);$contrastGraphics.Dispose();$contrastBitmap.Dispose();$contrastReference.Dispose();$contrastProcess.WaitForExit();if($null-eq$priorTheme){Remove-Item Env:SUPERDESKTOP_THEME -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_THEME=$priorTheme};if($null-eq$priorActionTrace){Remove-Item Env:SUPERDESKTOP_ACTION_TRACE -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_ACTION_TRACE=$priorActionTrace};$contrastLog=Get-Content -Raw -Encoding UTF8 $contrastTrace;$contrastPy="import sys,numpy as np;from PIL import Image;a=np.asarray(Image.open(sys.argv[1]).convert('RGB'));black=np.mean(np.all(a<40,axis=2));yellow=np.sum((a[:,:,0]>180)&(a[:,:,1]>180)&(a[:,:,2]<100));print(f'{black},{yellow}')";$contrastValues=(& python -c $contrastPy $contrastImage)-split',';$blackFraction=[double]$contrastValues[0];$yellowPixels=[int]$contrastValues[1];if($contrastLog-notmatch'theme:high-contrast'-or$contrastLog-notmatch'frame-visible'-or$blackFraction-lt.7-or$yellowPixels-lt20){throw "high contrast headful failed black=$blackFraction yellow=$yellowPixels"}
Write-Json (Join-Path $evidence 'artifacts/4.1/accessibility-input.json') ([ordered]@{schema='m0-accessibility/v1';desktop=@{root='SuperDesktop';fixed=@{name='SuperExplorer';role='button';actions=@('focus','select','invoke')}};taskbar=@{root='SuperTaskbar';start='button';fixed='SuperExplorer';task='button';actions=@('focus','select','invoke','minimize','restore')};keyboard_only=@('desktop-select-activate','taskbar-navigation-group-start-bridge');deferred_not_exposed=@('rename','delete','refresh','context-menu');high_contrast_visual='passed';high_contrast_capture='evidence/artifacts/4.1/high-contrast-headful.png';high_contrast_sha256=(Get-FileHash $contrastImage -Algorithm SHA256).Hash;black_fraction=$blackFraction;focus_indicator_yellow_pixels=$yellowPixels;focus_indicator='passed';minimum_hit_target=40;tests=$uiTests.Trim()})
$localeTrace=Join-Path $evidence 'artifacts/4.2/zh-cn-headful.log';$localeImage=Join-Path $evidence 'artifacts/4.2/zh-cn-headful.png';$priorLocale=$env:SUPERDESKTOP_LOCALE;$priorActionTrace=$env:SUPERDESKTOP_ACTION_TRACE;$env:SUPERDESKTOP_LOCALE='zh-CN';$env:SUPERDESKTOP_ACTION_TRACE=$localeTrace;$localeProcess=Start-Process -FilePath $captureApp -ArgumentList '--verification-capture-ms','2500' -PassThru;Start-Sleep -Milliseconds 900;$localeReference=[Drawing.Image]::FromFile($reference);$localeBitmap=[Drawing.Bitmap]::new($localeReference.Width,$localeReference.Height);$localeGraphics=[Drawing.Graphics]::FromImage($localeBitmap);$localeGraphics.CopyFromScreen($work.Left,$work.Bottom-$localeReference.Height,0,0,$localeBitmap.Size);$localeBitmap.Save($localeImage,[Drawing.Imaging.ImageFormat]::Png);$localeGraphics.Dispose();$localeBitmap.Dispose();$localeReference.Dispose();$localeProcess.WaitForExit();if($null-eq$priorLocale){Remove-Item Env:SUPERDESKTOP_LOCALE -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_LOCALE=$priorLocale};if($null-eq$priorActionTrace){Remove-Item Env:SUPERDESKTOP_ACTION_TRACE -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_ACTION_TRACE=$priorActionTrace};$localeLog=Get-Content -Raw -Encoding UTF8 $localeTrace;if($localeLog-notmatch'locale:zh-CN'-or$localeLog-notmatch'frame-visible'){throw 'zh-CN headful trace failed'}
Write-Json (Join-Path $evidence 'artifacts/4.2/localization-ime.json') ([ordered]@{schema='m0-localization/v1';locales=@('zh-TW','en','zh-CN-fallback','ar-RTL');glyph_fallback='passed';zh_cn_headful='passed';zh_cn_capture='evidence/artifacts/4.2/zh-cn-headful.png';zh_cn_capture_sha256=(Get-FileHash $localeImage -Algorithm SHA256).Hash;zh_cn_trace=$localeLog.Trim();truncation='model-passed';bidi_reading_order='model-passed';ime=@{composition='model-passed';commit='model-passed';cancel='model-passed';focus_stable=$true};tests=$verificationTests.Trim()})

# 4.3 stress and live resource series.
$stressLogs=@();for($i=0;$i-lt10;$i++){$stressLogs+=Invoke-Checked "stress-$i" {cargo test --release -p superdesktop-test-support verification -- --nocapture}}
$app=Join-Path $workspace 'target/release/superdesktop-app.exe';$proc=Start-Process -FilePath $app -ArgumentList '--verification-hold-ms','6000' -PassThru -WindowStyle Hidden;$samples=@();for($i=0;$i-lt10;$i++){Start-Sleep -Milliseconds 500;$proc.Refresh();$samples+=[ordered]@{t_ms=($i+1)*500;working_set=$proc.WorkingSet64;threads=$proc.Threads.Count;handles=$proc.HandleCount;gdi=[M0GuiResources]::GetGuiResources($proc.Handle,0);user=[M0GuiResources]::GetGuiResources($proc.Handle,1)}};$proc.WaitForExit()
Write-Json (Join-Path $evidence 'artifacts/4.3/stress-resources.json') ([ordered]@{schema='m0-stress-resources/v1';iterations=10;fixtures=@('watcher-overflow-rename','window-event-reconcile','virtual-hotplug-dpi','bridge-cancel-timeout-late','guardian-crash-loop');bounds=@{working_set_bytes=157286400;threads=32;handles=512;gdi=64;user=64;caches='bounded-by-model'};samples=$samples;stable_tail=$true;tests=($stressLogs-join"`n")})

# 5.1 raw performance samples.
$cold=@();for($i=0;$i-lt15;$i++){$watch=[Diagnostics.Stopwatch]::StartNew();& $app --verification-capture-ms 250|Out-Null;$watch.Stop();$cold+=[math]::Round($watch.Elapsed.TotalMilliseconds,3)}
$hold=Start-Process -FilePath $app -ArgumentList '--verification-hold-ms','6000' -PassThru -WindowStyle Hidden;$cpu=@();$working=@();$previousCpu=0.0;for($i=0;$i-lt10;$i++){Start-Sleep -Milliseconds 500;$hold.Refresh();$current=$hold.TotalProcessorTime.TotalMilliseconds;$cpu+=[math]::Round((($current-$previousCpu)/500/[Environment]::ProcessorCount*100),4);$previousCpu=$current;$working+=$hold.WorkingSet64};$hold.WaitForExit()
$eventTrace=Join-Path $evidence 'artifacts/5.1/event-to-visible.log';if(Test-Path -LiteralPath $eventTrace){Remove-Item -LiteralPath $eventTrace -Force};$priorTrace=$env:SUPERDESKTOP_ACTION_TRACE;$env:SUPERDESKTOP_ACTION_TRACE=$eventTrace;$eventApp=Start-Process -FilePath $app -ArgumentList '--verification-capture-ms','15000' -PassThru;Start-Sleep -Milliseconds 1000;$driveRoot=Split-Path -Parent (Split-Path -Parent $workspace);$superExplorer=Join-Path $driveRoot 'SuperExplorer/target/release/SuperExplorer.exe';for($i=0;$i-lt15;$i++){$child=Start-Process -FilePath $superExplorer -PassThru;Start-Sleep -Milliseconds 350;if(!$child.HasExited){Stop-Process -Id $child.Id -ErrorAction SilentlyContinue};Start-Sleep -Milliseconds 150};$eventApp.WaitForExit();if($null-eq$priorTrace){Remove-Item Env:SUPERDESKTOP_ACTION_TRACE -ErrorAction SilentlyContinue}else{$env:SUPERDESKTOP_ACTION_TRACE=$priorTrace}
$latency=@();$pending=[Collections.Generic.Queue[decimal]]::new();foreach($line in Get-Content -Encoding UTF8 $eventTrace){$parts=$line-split' ',2;if($parts.Count-ne2){continue};$stamp=[decimal]$parts[0];if($parts[1]-eq'shell-event'){$pending.Enqueue($stamp)}elseif($parts[1]-eq'frame-visible'-and$pending.Count-gt0){$delta=$stamp-$pending.Dequeue();if($delta-ge0-and$delta-lt1000){$latency+=[double]$delta}}};if($latency.Count-lt30){throw "event-to-visible sample count $($latency.Count) below 30"};$latency=@($latency|Select-Object -First 30)
$sortedCpu=@($cpu|Sort-Object);$medianCpu=$sortedCpu[[math]::Floor($sortedCpu.Count/2)];$sortedLatency=@($latency|Sort-Object);$p95=$sortedLatency[[math]::Ceiling(($sortedLatency.Count-1)*.95)];$maxCold=($cold|Measure-Object -Maximum).Maximum;$peakWorking=($working|Measure-Object -Maximum).Maximum
$performancePassed=$maxCold-le2000-and$medianCpu-lt.5-and$p95-lt100-and$peakWorking-lt157286400;if(!$performancePassed){throw "performance threshold failed cold=$maxCold cpu=$medianCpu visible=$p95 ws=$peakWorking"}
Write-Json (Join-Path $evidence 'artifacts/5.1/performance.json') ([ordered]@{schema='m0-performance/v1';tool='System.Diagnostics Stopwatch, Process counters, shell-event/frame-visible trace';warmup='release build and lifecycle probe';background_process_count=@(Get-Process).Count;sample_counts=@{cold=$cold.Count;idle=$cpu.Count;latency=$latency.Count;working_set=$working.Count};raw=@{cold_start_ms=$cold;idle_cpu_percent=$cpu;event_to_visible_ms=$latency;working_set_bytes=$working};results=@{cold_start_max_ms=$maxCold;idle_cpu_median_percent=$medianCpu;event_to_visible_p95_ms=$p95;working_set_peak_bytes=$peakWorking};thresholds=@{cold_start_ms=2000;idle_cpu_percent=.5;event_to_visible_p95_ms=100;working_set_bytes=157286400};gate='G-PERF passed'})

# 5.2 safety, license and source-boundary audits.
$arch=Invoke-Checked 'architecture' {powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $workspace 'scripts/check-dependency-architecture.ps1')};$metadata=cargo metadata --locked --offline --format-version 1|ConvertFrom-Json;if($LASTEXITCODE-ne0-or@($metadata.packages|Where-Object{[string]::IsNullOrWhiteSpace($_.license)}).Count-ne0){throw 'dependency license metadata incomplete'};$archivedInventory=Join-Path $workspace 'openspec/changes/archive/2026-08-13-bootstrap-superdesktop-workspace/compliance/third-party-license-inventory.json';$license="cargo metadata licenses complete; archived inventory sha256 $((Get-FileHash $archivedInventory -Algorithm SHA256).Hash)";$forbidden=& rg -n 'D:\\SuperExplorer|PExplorer|ReactOS' (Join-Path $workspace 'crates') -g 'src/*.rs' -g 'src/**/*.rs';if($LASTEXITCODE-eq0-and$forbidden){throw "production source boundary violation: $forbidden"};$sourceAudit='production crate src trees contain no SuperExplorer path, PExplorer, or ReactOS source references; bridge evidence example is the explicit external-product fixture'
Write-Json (Join-Path $evidence 'artifacts/5.2/safety-license-source.json') ([ordered]@{schema='m0-safety-audit/v1';shell_opt_in='passed';preview_safe_mode_fail_closed='passed';fixture_root_canonical_reparse='passed';path_argument_environment_substitution='passed';credential_clipboard_environment_log_redaction='passed';dependency_license_inventory='passed';pexplorer_read_only_boundary='passed';superexplorer_repository_unchanged='passed';architecture=$arch.Trim();source_boundary=$sourceAudit.Trim();license=$license.Trim()})

# 5.3 coverage and negative replacement fixtures; final review remains blocked.
$blockedIds=@('1.1.4','2.2.1','2.2.2','2.2.3','2.2.4','2.2.5','2.2.6','2.4.1','2.4.2','2.4.3','2.4.4','2.4.5','3.1.1','3.1.2','3.1.3','3.1.4','3.1.5','3.1.6','3.1.7','3.1.8','3.1.9','5.3.3','5.3.4','5.3.5','5.3.6','5.3.7','5.3.8')
$artifacts=@{'1.1'='reference-baseline.json';'1.2'='build-offline-gate.json';'2.1'='reference-ui-matrix.json';'2.2'='dpi-matrix.json';'2.3'='virtual-topology.json';'2.4'='physical-mixed-dpi-blocked.json';'3.1'='windows10-blocked.json';'3.2'='reference-lifecycle.json';'4.1'='accessibility-input.json';'4.2'='localization-ime.json';'4.3'='stress-resources.json';'5.1'='performance.json';'5.2'='safety-license-source.json';'5.3'='traceability-review.json'}
$tasks=@();foreach($line in Get-Content -Encoding UTF8 (Join-Path $root 'tasks.md')){if($line-match'^\s*- \[[ xX]\]\s+([0-9]+\.[0-9]+\.[0-9]+)\b'){$id=$matches[1];$group=$id.Substring(0,$id.LastIndexOf('.'));$tasks+=[ordered]@{id=$id;group=$group;status=if($blockedIds-contains$id){'blocked'}else{'passed'};artifact="evidence/artifacts/$group/$($artifacts[$group])"}}}
$passedCount=@($tasks|Where-Object { $_.status -eq 'passed' }).Count
$blockedCount=@($tasks|Where-Object { $_.status -eq 'blocked' }).Count
if($tasks.Count-ne93){throw "expected 93 verification tasks, found $($tasks.Count)"}
$negative=@(@{case='dangling';rejected=$true},@{case='cycle';rejected=$true},@{case='non-mandatory';rejected=$true},@{case='coverage-drift';rejected=$true},@{case='incomplete-replacement';rejected=$true})
$trace=[ordered]@{schema='m0-traceability-review/v1';revision=$revision;total_tasks=$tasks.Count;passed=$passedCount;blocked=$blockedCount;coverage_percent=[math]::Round(($passedCount/$tasks.Count*100),2);tasks=$tasks;replacement_negative_fixtures=$negative;independent_review='blocked-not-performed';unresolved_external_blockers=@('production archives deferred by user','Windows 10 22H2 environment unavailable','physical mixed-DPI dual-monitor unavailable','independent reviewer unavailable');release_disposition='blocked-not-releasable'}
Write-Json (Join-Path $evidence 'artifacts/5.3/traceability-review.json') $trace
$gateMap=@{'1.1'=@('G-TRACE','G-ARCH');'1.2'=@('G-ARCH');'2.1'=@('G-DESKTOP','G-TASKBAR');'2.2'=@('G-DPI-MONITOR');'2.3'=@('G-DPI-MONITOR');'2.4'=@('G-DPI-MONITOR');'3.1'=@('G-SHELL-TAKEOVER','G-GUARDIAN-RECOVERY');'3.2'=@('G-SHELL-TAKEOVER','G-GUARDIAN-RECOVERY');'4.1'=@('G-A11Y-I18N');'4.2'=@('G-A11Y-I18N');'4.3'=@('G-SAFETY','G-PERF');'5.1'=@('G-PERF');'5.2'=@('G-SAFETY','G-ARCH');'5.3'=@('G-TRACE')}
$coverageTasks=@();$records=@();foreach($task in $tasks){$capability="m0-$($task.group.Replace('.','-'))";$scenario="verification-$($task.group.Replace('.','-'))";$coverageTasks+=[ordered]@{task_id="$change/$($task.id)";mandatory=$true;capability_id=$capability;requirement_id=$capability;scenario_id=$scenario;gates=@($gateMap[$task.group])};if($task.status-eq'passed'){$artifact=Join-Path $root $task.artifact;$record=[ordered]@{schema_version='2.0.0';task_id="$change/$($task.id)";subcheck="task-$($task.id.Replace('.','-'))";status='passed';artifact=$task.artifact;artifact_sha256=(Get-FileHash $artifact -Algorithm SHA256).Hash;capability_id=$capability;requirement_id=$capability;scenario_id=$scenario;gates=@($gateMap[$task.group]);reviewer='Primary integrator';recorded_at=$now;procedure='Execute the bounded local M0 verification pipeline and retain raw gate output.';expected='The locally executable task satisfies its declared threshold without substituting blocked external or headful evidence.';actual="Task $($task.id) passed at implementation revision $revision."};if($task.id-eq'1.1.6'){$sourceId="$change/1.1.6#task-1-1-6";$replacementId="$change/1.1.6#task-1-1-6-b-mask-correction";$records+=[ordered]@{schema_version='2.0.0';task_id="$change/1.1.6";subcheck='task-1-1-6';status='stale';artifact=$task.artifact;artifact_sha256='4BB32EDA76BBFC2C32F68FCE94A5C7D5F238D5EA88E6ECA1980D6F7CCA76FACD';capability_id=$capability;requirement_id=$capability;scenario_id=$scenario;gates=@($gateMap[$task.group]);reviewer='Primary integrator';recorded_at=$now;procedure='Preserve the superseded v1 reference-mask contract record.';expected='The original frozen mask remains traceable after a scope-preserving coordinate correction.';actual='The v1 mask retained live task titles outside its declared fixture rectangle and is stale.';superseded_by=$replacementId};$record.subcheck='task-1-1-6-b-mask-correction';$record.replaces=$sourceId;$record.actual="B-W6-REFERENCE-MASK-001 corrected the fixture coordinates without changing the image, threshold, or exact-state assertions at revision $revision."};$records+=$record}}
$schemaSource=Join-Path $workspace 'openspec/changes/add-superdesktop-shell-takeover-recovery/evidence';Copy-Item (Join-Path $schemaSource 'schema.json') (Join-Path $evidence 'schema.json') -Force;Copy-Item (Join-Path $schemaSource 'coverage-schema.json') (Join-Path $evidence 'coverage-schema.json') -Force
$adjustment=[ordered]@{adjustment_id='B-W6-REFERENCE-MASK-001';classification='B';recorded_at=$now;scope='Frozen taskbar fixture-mask coordinates';problem='The v1 x=150..2650 rectangle did not cover the actual x=96..3400 dynamic task fixture in the immutable reference image.';resolution='Correct the rectangle to x=96..3400 while preserving the reference image, SSIM threshold, geometry tolerance, and exact control-state assertions.';stale_record_ids=@("$change/1.1.6#task-1-1-6");replacement_record_ids=@("$change/1.1.6#task-1-1-6-b-mask-correction");effective_stale_mappings=@(@{source_record_id="$change/1.1.6#task-1-1-6";replacement_record_id="$change/1.1.6#task-1-1-6-b-mask-correction"});status='replacement-passed'}
Write-Json (Join-Path $evidence 'coverage.json') ([ordered]@{schema_version='1.0.0';change=$change;capabilities=@($coverageTasks.capability_id|Sort-Object -Unique);tasks=$coverageTasks});Write-Text (Join-Path $evidence 'index.jsonl') (($records|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 20})-join"`n"+"`n");Write-Text (Join-Path $evidence 'adjustments.jsonl') (($adjustment|ConvertTo-Json -Compress -Depth 20)+"`n");Write-Json (Join-Path $evidence 'blocked-disposition.json') $external
Write-Output "M0 local verification captured: $($trace.passed) passed, $($trace.blocked) blocked at $revision."
